Trynow btn fix
formbricks/formbricks pull request #1013
Opened 2023-10-08 11:38 UTC by ratishjain12

## What does this PR do?

I have fixed this issue @jobenjada 

Fixes #1012 

![image](https://github.com/formbricks/formbricks/assets/43003421/56fbeb1d-2d73-49e9-ba6d-7ac70f964131)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2023-10-08 13:26 UTC, ShubhamPalriwala requested changes
Hey, thanks a lot for finding the bug and opening a PR as well. The button looks better now. A couple of small nits from my end, once that's done, we're good to go 🚀

2023-10-08 13:26 UTC, ShubhamPalriwala commented on apps/formbricks-com/components/shared/UseCaseCTA.tsx
> +          className="bg-gray-800 text-gray-500 hover:text-white"
Can you make the text more lighter for the dark mode? It looks really off currently. And can you also handle the text coloring being dynamic as per the light/dark mode as well? The text isn't really visible in the light mode:
![image](https://github.com/formbricks/formbricks/assets/55556994/07b934d9-7077-4ad7-ab07-88593a53c203)

2023-10-08 13:26 UTC, ShubhamPalriwala commented on apps/formbricks-com/components/shared/Header.tsx
Can you revert the changes that aren't needed from this file? I don't think we need them in the context of this PR and are not adding value to the affected UseCTA component as well.

2023-10-08 15:23 UTC, ratishjain12 commented
> Hey, thanks a lot for finding the bug and opening a PR as well. The button looks better now. A couple of small nits from my end, once that's done, we're good to go 🚀 

Sure 👍

2023-10-08 15:30 UTC, ratishjain12 commented
@ShubhamPalriwala  is this fine?
![image](https://github.com/formbricks/formbricks/assets/43003421/1a16889a-962d-468e-92cb-d9067ce0663d)

2023-10-08 17:35 UTC, ShubhamPalriwala commented
Great work @ratishjain12, looks good now 🚀

2023-10-08 17:35 UTC, ShubhamPalriwala approved these changes

2023-10-08 17:36 UTC, ratishjain12 commented
> Great work @ratishjain12, looks good now 🚀

Thanks looking forward to contribute more

2023-10-09 04:36 UTC, merged

2023-10-09 05:59 UTC, ratishjain12 commented
> > Great work @ratishjain12, looks good now 🚀
> 
> Thanks looking forward to contribute more

@ShubhamPalriwala can you add hacktoberfest labels on this?