fix: encryption keys
formbricks/formbricks pull request #1094
Opened 2023-10-11 12:04 UTC by pandeymangg

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2023-10-11 13:32 UTC, mattinannt requested changes
@pandeymangg thanks a lot for the PR :-) Looks good in general, just had a few comments ;-)

2023-10-11 13:32 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/actions.ts
>  export async function generateSingleUseIdAction(isEncrypted: boolean): Promise<string> {
if you currently have this open, please add auth :-)

2023-10-11 13:32 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/page.tsx
> +  const isEncryptionKeySet = !!ENCRYPTION_KEY;
I think we can skip this as it's not possible to not have the ENCRYPTION_KEY set. So please also remove the disabled state of the encryption toggle together with the tooltip :-)

2023-10-11 13:32 UTC, mattinannt commented on apps/web/lib/singleUseSurveys.ts
> +  if (!ENCRYPTION_KEY) {
ENCRYPTION_KEY is required so you can remove this check

2023-10-11 13:32 UTC, mattinannt commented on apps/web/lib/singleUseSurveys.ts
> +  if (!ENCRYPTION_KEY) {
ENCRYPTION_KEY is required so you can remove this check

2023-10-12 15:13 UTC, PratikAwaik commented on apps/web/lib/singleUseSurveys.ts
> +    if (surveySingleUseId.length === 64) {
@pandeymangg Why did you add a check of length === 64 here? Also why did you use AES128 for 64-length string and symmetric decrypt for string of length other than 64?

2023-10-17 10:23 UTC, mattinannt approved these changes
🙏

2023-10-19 08:23 UTC, merged