feat: survey error modal/page
formbricks/formbricks pull request #1140
Opened 2023-10-14 07:51 UTC by ty-kerr

## What does this PR do?

Adds an error page and error modal for link surveys and in-app surveys respectively for when submission of responses have failed more than the number of retries alloted. The error page/modal shows all the respones from the survey and has two button, Copy all response as json, and send to email. 

Fixes #1082

https://www.loom.com/share/a04569b18f8e4bf8bcf402f9bfb2611e

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Create a link survey or in-app survey, Mock response submission failure in responseQueue.ts, by fixing success to false on line 46. Complete the survey and wait 3 seconds after the thank you page is shown. The error page should appear

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [] Updated the Formbricks Docs if changes were necessary

2023-10-14 07:55 UTC, ty-kerr commented on packages/surveys/src/components/OpenTextQuestion.tsx
> -        onSubmit({ [question.id]: value, inputType: question.inputType });
remove this as it was added unused fields to the response accumulator

2023-10-14 16:41 UTC, jobenjada commented
Works well :) 

@pandeymangg please review

2023-10-21 13:46 UTC, pandeymangg requested changes
Thanks a lot for the PR @ty-kerr. Looks and works great! 🙌  The code also looks great!
Please also add the loading state for the `EditTeamSupportEmail` component in `apps/web/app/(app)/environments/[environmentId]/settings/members/loading.tsx` 😊 and use the `email` type for supportEmail as I've mentioned below.
Thanks a lot!

2023-10-21 13:46 UTC, pandeymangg commented on packages/types/v1/teams.ts
> +  supportEmail: z.string().nullable(),
please use `z.string().email().nullable()` 🙏

2023-10-21 13:46 UTC, pandeymangg commented on packages/types/v1/teams.ts
> +  supportEmail: z.string().nullish(),
please use `z.string().email().nullish()` 🙏

2023-10-23 07:36 UTC, ty-kerr commented
@pandeymangg 
Done with the changes from review and merged with main and resolved all conflicts. XD

2024-01-22 15:37 UTC, mattinannt approved these changes
@ty-kerr Thanks again for the PR and your great work on this feature 💪🔥🚀

As you may have noticed, we've had some internal discussions about the feature, it's scope and how it fits into our current Formbricks strategy.

We've decided to redesign the feature a bit; remove the support email address to have all feedback sent to the Formbricks platform and use the error modal to signal the user that their feedback can't be sent (probably because their internet connection isn't working).

(We are working on another feature to increase the availability of Formbricks Cloud, which makes the failure to send from our side very unrealistic.)

I have now made all the changes for this and we are ready to merge 💪 Sorry for the big delay 🙈

<img width="607" alt="Screenshot 2024-01-22 at 16 36 15" src="https://github.com/formbricks/formbricks/assets/675065/7d182f0f-db3f-440c-b565-d9eb97d5af62">

2024-01-22 15:48 UTC, merged