Feat/notion integration
formbricks/formbricks pull request #1197
Opened 2023-10-15 14:37 UTC by PratikAwaik

## What does this PR do?

- Adds notion integration

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [x] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2023-10-15 20:19 UTC, jobenjada commented
@PratikAwaik thanks a ton, really excited to try this out :) 

Can you add a barebones docs page so I know what to do to test this locally? :) I can then just rewrite it into a fully fledged docs page and it can go live together 😍

2023-10-16 06:52 UTC, PratikAwaik commented
@jobenjada Sure thing. Will let you know once done

2023-10-18 19:15 UTC, jobenjada commented
Hey @PratikAwaik - thanks a lot for shipping this :))

-----

1. Databases not pulled in after setup - delay:

When I set it up, I couldn't select any of the databases for a good minute. Suddenly, it worked. Any idea why this could be? And how we could prevent the impression that it doesnt work?

I think we should have some kind of loading indicator, because when I checked back in later on, I found 20 in the list. We should convey to the user that we're still loading all databases from Notion.


--------

2. Wording:  "Map Formbricks fields to Notion property"

Im not really sure what this tells me :)

<img width="878" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d14e5097-88e9-45d4-ac86-048b54f218ad">

Oh I think there is the mapping UI missing, no?

<img width="919" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/aed030d4-0e4f-4a7d-a804-cf249e2058b1">


------

3. Error message when editing existing integration

<img width="978" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/f8ecee21-ffe0-4c6d-8c2f-fc26922972f4">

When I click on an integration to make changes to it, I'm getting the above error. In order to keep the solution simple, let's just change the error message to this:

"A connection with this database is live. Please make changes with caution."

--------

I wasn't able to test the integration end-to-end.

If you can please also resolve merge conflicts and merge main :)

2023-10-19 16:49 UTC, jobenjada commented
Hey!

Now the UI is here :)

Does the Notion API allow to request an updated version of a database? I think we need some kind of 'Refresh' button. I just created new fields in the Notion database but they dont show up in the Formbricks integration:

<img width="913" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/8ab6ce16-73c4-4c3f-963e-ad474664dd26">

-------

Secondly: Great job on the mapping UI, it looks really slick!! 🔥

In-between testing, the mapping UI got lost:

https://tella.video/johanness-video-8419

------

Questions do not get reduced from the list when they are selected once:

<img width="381" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/e4d86b7f-63ac-44a0-b447-0211a3dd7d37">


I think it makes sense, maybe people want to add the same info twice. Just double checking with you if this was the intention :)

-----

Just double checking if "URI" is correct or if it should be "URL":

<img width="347" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/5ee100a9-b963-41e8-95a6-eb91a9e9c59a">

------

<img width="799" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/f20d2449-17b6-4372-87ba-ba10d36164aa">

Great to validate that early! What would I map CTA on? I thought its either boolean ( clicked / dismissed )

Do you have a list of what question types you can map on which fields in Notion? Would love to include it to the Docs!

-----

Please disable the button if an error message is visible:

<img width="889" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/645ab18f-3957-4e31-
9ca2-e46f1da5b579">

-----

The new map input is not added below the entry where we hit +

https://tella.video/johanness-video-dz5k

-----

Lastly: The integration doesnt pipe the answers to Notion :(

Not sure what causes it, didnt get an error in the console either.

https://tella.video/johanness-video-6yso

----

### Thanks!!

It's really coming together, excited to have this in the upcoming weekly review 🤓

2023-10-20 11:54 UTC, PratikAwaik commented
1. Checking
2. The mapping UI disappearing is not reproducible from my end. Not sure why that would be happening.
3. That's correct. People might want to add the same info twice.
4. Notion docs says redirect URI, so I've kept URI.
5. Mapping List (its in constants.ts as well)
 
 ```
 TYPE_MAPPING = {
  cta: [],
  multipleChoiceMulti: ["multi_select"],
  multipleChoiceSingle: ["select", "status"],
  openText: [
    "created_by",
    "created_time",
    "date",
    "email",
    "last_edited_by",
    "last_edited_time",
    "number",
    "phone_number",
    "rich_text",
    "title",
    "url",
  ],
  nps: ["number"],
  consent: ["checkbox"],
  rating: ["number"],
};
```

5. Disabled the button when there are errors present.
6. 
<img width="928" alt="Screenshot 2023-10-20 at 5 22 56 PM" src="https://github.com/formbricks/formbricks/assets/54103265/890a29d9-a313-4149-812b-8a73b3535154">

I've fixed it like this.

**P.S:** Typeform also does the same


7. Sometimes, it might take some time for the answers to reflect in the database. Did you check notion after some time?

I've done fixes locally and working on other fixes. I'll update you once done.

2023-10-22 19:48 UTC, mattinannt requested changes
@PratikAwaik thank you for the PR :-) We also did some changes to the folder structure for the google sheets and airtable integration last week. Please check out the updated structure and make sure your integration fits right in :-)

2023-10-22 19:48 UTC, mattinannt commented on apps/formbricks-com/app/docs/integrations/notion/page.mdx
please put all the images in a subfolder `images`

2023-10-22 19:48 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/integrations/notion/AddIntegrationModal.tsx
please put this component in a subfolder `components`

2023-10-22 19:48 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/integrations/notion/Connect.tsx
please put this component in a subfolder `components`

2023-10-22 19:48 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/integrations/notion/Home.tsx
please put this component in a subfolder `components`

2023-10-22 19:48 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/integrations/notion/NotionWrapper.tsx
please put this component in a subfolder `components`

2023-10-22 19:48 UTC, mattinannt commented on packages/lib/notion/service.ts
> +export const getNotionIntegration = cache(
please check the latest changes from main. We now use the integration service to get the integration by type and only have the service for the integration, e.g. here the notion service, to communicate with notion

2023-10-22 19:48 UTC, mattinannt commented on packages/types/v1/integrations.ts
Please check the latest changes in the main branch and how we reorganised the types for the different integrations

2023-10-22 19:48 UTC, mattinannt commented on packages/lib/constants.ts
> +export const NOTION_REDIRECT_URI = env.NOTION_REDIRECT_URI;
isn't the NOTION_REDIRECT_URI always the same and `${WEBAPP_URL}/api/...callback`?
If so, please use this instead of a new environment variable

2023-10-22 19:48 UTC, mattinannt commented on apps/web/app/api/notion/route.ts
please check the latest changes in main and move the notion route to `apps/web/app/api/v1/integrations/notion/callback/route.ts`

2023-10-30 11:51 UTC, jobenjada commented
@PratikAwaik works really well! :) 

@mattinannt  ready for review / merge 🚀

2023-10-30 15:07 UTC, mattinannt requested changes
@PratikAwaik thanks a lot for the recent changes :-) 💪 There are a few things that need to be changes before this can be merged.
Please check my comments below 😊

2023-10-30 15:07 UTC, mattinannt commented on packages/types/integration/notion.ts
> +export type TNotionCredential = z.infer<typeof ZNotionCredential>;
please rename to `TIntegrationNotionCredential`

2023-10-30 15:07 UTC, mattinannt commented on packages/types/integration/notion.ts
> +export const ZNotionIntegration = z.object({
also here not following naming convention. Should be `ZIntegrationNotion` but this is already defined below?

2023-10-30 15:07 UTC, mattinannt commented on packages/types/integration/notion.ts
> +export const ZNotionDatabase = z.object({
please rename to `ZIntegrationNotionDatabase`

2023-10-30 15:07 UTC, mattinannt commented on packages/types/integration/notion.ts
> +export type TNotionDatabase = z.infer<typeof ZNotionDatabase>;
please rename to `TIntegrationNotionDatabase`

2023-10-30 18:10 UTC, PratikAwaik commented
@mattinannt resolved, please check and let me know if there any other changes required :)

2023-11-06 10:38 UTC, mattinannt commented
@Dhruwang I assigned this PR to you for review. Please make sure this PR is ready to get merged and also the latest changes we made for the Google Sheets & Airtable integration are also in this PR 😊💪

2023-11-14 05:11 UTC, Dhruwang approved these changes

2023-11-15 07:42 UTC, mattinannt reviewed
@Dhruwang thanks you for making the changes 😊💪 Can you please solve the latest merge conflicts and check the few things that I pointed out?
@jobenjada will do a final check on the functionality and then we can merge this :-)

2023-11-15 07:42 UTC, mattinannt commented on packages/lib/notion/service.ts
> +    if (error instanceof Prisma.PrismaClientKnownRequestError) {
@Dhruwang please check

2023-11-15 07:42 UTC, mattinannt commented on packages/lib/notion/service.ts
> +    if (error instanceof Prisma.PrismaClientKnownRequestError) {
@Dhruwang please check

2023-11-15 09:09 UTC, jobenjada commented
As discussed in Discord, for the record: 

1. Pls let Consent questions fill a checkbox field at Notion (true if clicked, false if skipped)
2. PictureSelect: Can we pipe the image through to Notion?
3. File Upload coming soon, but can be done once its live
4. Hidden Fields: Add hidden fields to the select list and map them on openText in Notion 

Thanks!! 🙏

2023-12-01 18:25 UTC, jobenjada commented
@PratikAwaik works smoooooothly, great work!! 

Matti pls have a look if the setup process is intuitive and well documented and last look at the migration and then LGTM por fiiiin :)

2023-12-14 13:08 UTC, mattinannt approved these changes
@PratikAwaik Great job! 👏🚀
Sorry that it took us so long to merge this PR.

2023-12-14 13:16 UTC, merged