feat: Introduce FileUpload Question
formbricks/formbricks pull request #1277
Opened 2023-10-17 20:19 UTC by KapadiaNaitik

## What does this PR do?
Add File Upload Question

Fixes #1257  (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create new question from the survey editor

## Checklist

### Required
`Will Update During Final Review`
- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2023-10-30 08:37 UTC, jobenjada commented
Hey @KapadiaNaitik - thanks for shipping this :)

Here is my feedback:

1. File upload field size changing on "Allow multiple files"

Off
<img width="1286" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/4bb39a78-2f0d-4d16-8521-fcfc4ff30c66">


On
<img width="1289" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/650a43ac-b07d-44f9-a342-3e3ec05dd256">

--------

2. This is custom coded, but we already have a similar component in our settings cards:
<img width="640" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/74be1e20-95ce-4564-a008-98590ea32723">

For example this one:
<img width="655" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/850ee392-ed0a-4139-817e-3425744cb490">

For the means of consistency, please reuse the code form the settings card. We have a reusable input field which packs all the styling which is used there.

The text in the gray box should be: **Limit upload file size to [    ] MB.**

-------

3. File types settings

This isn't very clear. Do people add just the suffix or include the dot? Does it work if they do either? Is this a security risk for people to upload files with e.g. .js or .php etc?

We can tweak the UX of this later on, for now please just validate the input field to make sure people add max 4 letters and don't include the dot, any other symbols etc. Display senseful toasts if people try to input something which doesnt match the validation criteria:

<img width="356" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/773ef88a-0959-4784-ab4d-83381615c6cc">
 

-------

4. Single Response Card Display

Pls reuse the UI from the Summary Overview :)

<img width="1272" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/028a80e4-97b8-450d-b917-5c1b1b9b0417">

-------

5. In Summary: Download instead of display

When clicking on this file, it leads to previewing the file in the browser. Instead, it should download it:


--------

4. Logic Jumps missing

@pandeymangg can you add basic logic jumps? E.g. has uploaded file / has not uploaded file?

-----

5. Email Preview missing

If File Upload is the first question and the user hits on the Email Preview tab in the Share Link Survey modal, it will likely break.

@pandeymangg can you add the corresponding component to the email preview functionality?

2023-11-06 10:17 UTC, mattinannt requested changes

2023-11-06 10:17 UTC, mattinannt commented on packages/types/product.ts
> +  billingInfo: ZTeamBilling.optional(),
please remove this from the product service as we can easily get this from the team service and we don't want to query an additional table every time we request a product.

2023-11-06 10:17 UTC, mattinannt commented on packages/types/surveys.ts
> +  allowedFileTypes: z.array(ZAllowedFileExtension).optional(),
we sometimes have `fileExtensions` and sometimes `fileTypes`. Please choose one to be consistent 😊
I think `fileExtensions` is more common

2023-11-06 10:17 UTC, mattinannt commented on packages/surveys/src/components/ui/FileInput/index.tsx
the `ui` folder in components seem strange as we don't currently have this file convention in surveys package currently. Also in this PR were some attempts to change the component structure:
https://github.com/formbricks/formbricks/pull/916
Please check come up with a universal structure :-)

2023-11-06 10:17 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/FileUploadQuestionForm.tsx
> +import { TSurvey, TSurveyFileUploadQuestion } from "@formbricks/types/surveys";
please add `"use client";`

2023-11-13 15:04 UTC, jobenjada commented
@mattinannt these things I couldn't solve:

1. Better error message when someone tries to upload a too large image. It just says "Upload failed!" - in case we can detect that it happened bc the file size is above the free level, we should display the File Too Large error message.

If not, we should at least add "Try again with a smaller file."

---------

2. When a file is deleted out of the uploader, the selection window is always opened again. I don't like the UX, bc when you delete something you dont necessarily want to upload a new file.

I've tried stopPropagation and moving the input a level up to not be a child but a sibling of the label (as GPT suggested). Can you fix this?

--------

Rest works well :)

2023-11-21 12:08 UTC, danielehrhardt commented
> @mattinannt these things I couldn't solve:
> 
> 1. Better error message when someone tries to upload a too large image. It just says "Upload failed!" - in case we can detect that it happened bc the file size is above the free level, we should display the File Too Large error message.
> 
> If not, we should at least add "Try again with a smaller file."
> 
> 2. When a file is deleted out of the uploader, the selection window is always opened again. I don't like the UX, bc when you delete something you dont necessarily want to upload a new file.
> 
> I've tried stopPropagation and moving the input a level up to not be a child but a sibling of the label (as GPT suggested). Can you fix this?
> 
> Rest works well :)

Works great. Would like to see it in the next release <3

2023-11-23 04:44 UTC, pandeymangg commented
The upload functionality is not working for in-app surveys right now, this is due to an overlook in the FileUpload component, will fix this today so that this can get closed 💪

2023-11-23 09:58 UTC, mattinannt commented on packages/js/src/lib/widget.ts
> +        console.log({
pleas remove

2023-11-23 10:01 UTC, mattinannt commented on packages/surveys/src/components/general/FileInput.tsx
> +// import { uploadFile } from "../../lib/uploadFile";
please remove comment :-)

2023-11-23 10:01 UTC, mattinannt commented on packages/surveys/src/components/general/FileInput.tsx
> +            // const response = await uploadFile(file, allowedFileExtensions, surveyId, environmentId);
please remove comment :-)

2023-11-23 10:01 UTC, mattinannt commented on packages/surveys/src/components/general/FileInput.tsx
> +          // const response = await uploadFile(file, allowedFileExtensions, surveyId, environmentId);
please remove comment :-)

2023-11-23 10:01 UTC, mattinannt commented on packages/surveys/src/components/general/FileInput.tsx
> +                // const response = await uploadFile(file, allowedFileExtensions, surveyId, environmentId);
please remove comment :-)

2023-11-23 10:01 UTC, mattinannt commented on packages/surveys/src/components/general/FileInput.tsx
> +              // const response = await uploadFile(file, allowedFileExtensions, surveyId, environmentId);
please remove comment :-)

2023-11-23 14:47 UTC, jobenjada approved these changes

2023-11-23 14:52 UTC, merged