feat: adds image to open text question
formbricks/formbricks pull request #1305
Opened 2023-10-19 01:31 UTC by rtpa25

## What does this PR do?

Fixes #1258 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2023-10-19 03:05 UTC, rtpa25 commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/CTAQuestionForm.tsx
> +          </div>
Refactor into a separate component

2023-10-19 03:05 UTC, rtpa25 commented on apps/web/package.json
> +    "next": "13.5.6",
https://github.com/vercel/next.js/issues/56947 <Reason for patch upgrade>

2023-10-19 03:25 UTC, rtpa25 commented
LGTM

2023-10-19 10:03 UTC, rtpa25 commented
@anjy7 Not necessarily, UI components are Input, Label etc which do not have any business specific logic, but this has packages/ui is the ui library of a product, this does not belong there IMO thoughts @mattinannt

2023-10-19 13:01 UTC, neilchauhan2 requested changes
@rtpa25 Thank you so much for your contribution 🎉. The functionality is working great, but I have mentioned a few issues, could you please address them. I'll review this PR again post that.

cc: @mattinannt

2023-10-19 13:23 UTC, rtpa25 commented on pnpm-lock.yaml
> +      caniuse-lite: 1.0.30001547
Devs don't change lock files, I have just upgraded the nextjs version as mentioned here https://github.com/formbricks/formbricks/pull/1305#discussion_r1364823631. These are peer deps for that, I have no control over that

2023-10-19 13:23 UTC, rtpa25 commented on pnpm-lock.yaml
> +        version: 1.10.12
as I said below

2023-10-19 13:25 UTC, rtpa25 commented on packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
> +      )}
The es-lint rule is wrong hence warning too, this package is written with preact, can't access next image here. Can in dev cause of turbo common node_modules, but not in prod

2023-10-19 13:26 UTC, rtpa25 commented on packages/surveys/src/components/ConsentQuestion.tsx
> +        </div>
check comment below

2023-10-19 13:27 UTC, rtpa25 commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionFormInput.tsx
> +            onClick={() => setShowImageUploader((prev) => !prev)}
this is more readable as it's a one liner, and is repeated in a ton of places inside the codebase, creating separate handlers is unnecessary clutter and over head cause you need to give good names to them too

2023-10-19 13:28 UTC, rtpa25 commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/QuestionFormInput.tsx
> +            }}
Look at other places updateQuestion is being used and this https://github.com/formbricks/formbricks/pull/1305#discussion_r1365537336

2023-10-19 13:31 UTC, rtpa25 commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/edit/components/MultipleChoiceMultiForm.tsx
> +        ref={questionRef}
it routes back to the Input inside the questionforminput component as used above

2023-10-20 10:34 UTC, neilchauhan2 approved these changes

2023-10-20 10:35 UTC, neilchauhan2 commented
@mattinannt done with the review, could you please look into this.

2023-10-20 10:54 UTC, merged