feat: Time to complete Metadata
formbricks/formbricks pull request #1416
Opened 2023-10-23 05:49 UTC by Dhruwang

## What does this PR do?

Fixes #1104 
Adds time to complete metadata

<img width="1728" alt="Screenshot 2023-10-23 at 9 30 03 AM" src="https://github.com/formbricks/formbricks/assets/67850763/63e7d1ad-a131-4e55-ae07-b94af5bd634a">

**Little overview of the approach**
Whenever a question component is mounted, its time is stored in a variable named startTime
Now if user perform any of the three activities, (currentTime-startTime) is stored in response object
1. Click on Submit button
2. Clicks on Back Button
3. Switches Tab

Now when user arrives on same question again, above process runs again but now, new time is added to the previous one for that questionId

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Create a Survey
Take it
Check Time to complete in survey metadata

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2023-10-23 10:50 UTC, jobenjada commented
Hey! Works very well, except for one issue: The Multi Select Question Card doesnt work :(

https://tella.video/multi-select-not-working-3xf6

Not sure if related to your changes but on prod it works :)

2023-10-24 10:06 UTC, Dhruwang commented
Fixed multi select issue :)

2023-11-14 14:06 UTC, jobenjada commented
Hey Dhru!

unfortunately, your changes seem to break both the validation as well as the drop-off analyzer. here a video:

https://tella.video/johanness-video-693d

--------------

When you test it through, please make sure to create a survey with each question type at least once.

---------

Expanding scope: It would be great if we could display the avg time spent on each question in this table:

![image](https://github.com/formbricks/formbricks/assets/72809645/3cde93a9-9bac-4724-a4a1-deaedf18d83c)

What do you think? 🤓

2023-11-15 09:53 UTC, jobenjada commented
looks super nice, love the additional insight it offer! 🚀  @mattinannt pls merge

2023-11-29 14:41 UTC, mattinannt requested changes
@Dhruwang I solved the merge conflicts but still found a few things we can optimise before merging 😊

2023-11-29 14:41 UTC, mattinannt commented on packages/surveys/src/components/general/Survey.tsx
> +  const [ttcObj, setTtcObj] = useState<TResponseTtc>({});
`ttcObj` is not an ideal name. Can we just name it `ttc`?

2023-11-29 14:41 UTC, mattinannt commented on packages/surveys/src/components/questions/ConsentQuestion.tsx
> +  const [startTime, setStartTime] = useState(performance.now());
We have this code in all question types. Can we use a helper function or hook instead? e.g.

```ts
import { useEffect, useState } from 'react';

function useTtc(questionId, ttc, setTtc) {
  const [startTime, setStartTime] = useState(performance.now());

  useEffect(() => {
    setStartTime(performance.now());
  }, [questionId]);

  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        // Restart the timer when the tab becomes visible again
        setStartTime(performance.now());
      } else {
        const updatedTtc = getUpdatedTtc(
          ttc,
          questionId,
          performance.now() - startTime
        );
        setTtc(updatedTtc);
      }
    };

    // Attach the event listener
    document.addEventListener('visibilitychange', handleVisibilityChange);

    return () => {
      // Clean up the event listener when the component is unmounted
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, []);
}

export default useTtc;
```

```ts
import useTtc from '@/lib/useTtc';

function MyComponent({ question, ttcObj, setTtcObj }) {
  useVisibilityTimer(question.id, ttcObj, setTtcObj);

  // Rest of your component logic...
}
```

2023-11-29 14:41 UTC, mattinannt commented on packages/surveys/src/lib/utils.ts
> +export const getUpdatedTtcObj = (ttcObj: TResponseTtc, questionId: string, time: number) => {
since we now have more lib functions for this I think a `lib/ttc.ts` file could make sense :-)

2023-11-29 14:41 UTC, mattinannt commented on packages/lib/response/util.ts
> +export function calculateTotal(ttc: TResponseTtc) {
please rename to `calculateTtcTotal`

2023-11-30 14:28 UTC, merged