feat: support for make and n8n integration states
formbricks/formbricks pull request #1568
Opened 2023-11-03 09:28 UTC by ShubhamPalriwala

## What does this PR do?
Adds Integration States visibility for `make` and `n8n`:
![image](https://github.com/formbricks/formbricks/assets/55556994/6d54c7ce-165d-4ab8-a145-6c30c44a71ed)

We now need to pass this as a request body parameter in the make and n8n apps as well!

## Type of change
- [x] Enhancement (small improvements)

## How should this be tested?
- Use the create webhook API endpoint and pass in a "source" key in the json body with value as any of the allowed sources: "make", "n8n", "zapier", "user".
- Now once this webhook is created for the given source, it should reflect the same in the connection state.

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2023-11-05 13:51 UTC, mattinannt requested changes

2023-11-05 13:51 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx
> +      getCountOfWebhooksBasedOnSource(environmentId, "make"),
please rename function to `getWebhookCountBySource` to follow the current naming pattern better

2023-11-05 13:51 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/integrations/page.tsx
> +  const [environment, integrations, userWebhooks, zapierWebhooks, makeWebhooks, n8nwebhooks] =
the variable are named `zapierWebhooks`, `userWebhooks`, even though it's not the webhook but the count. Please rename to `zapierWebhookCount`, etc.

2023-11-05 13:51 UTC, mattinannt commented on packages/database/schema.prisma
>  enum WehbhookSource {
the typo is unfortunate ;-) 
Can we also rename this with the migration? ;-)

2023-11-05 13:51 UTC, mattinannt commented on packages/types/webhooks.ts
> +  source: z.enum(["user", "zapier", "make", "n8n"]),
since we have the source twice, please introduce a new variable `ZWebhookSource`

2023-11-06 04:56 UTC, ShubhamPalriwala commented
Hey @mattinannt, I've made the requested changes 🚀 One thing to keep in mind is, the migration is not backward compatible ie the older states of the webhook source will not be stored since its creating a new column and deleting the old one

2023-11-27 13:40 UTC, mattinannt approved these changes
@ShubhamPalriwala thanks a lot for the changes :-)💪🙏

2023-11-27 13:46 UTC, merged