add feeback app contest article
formbricks/formbricks pull request #1818
Opened 2023-12-21 15:47 UTC by SiR-PENt

## What does this PR do?

Add feedback app contest article to the blog

2023-12-21 21:06 UTC, jobenjada requested changes
Overall it looks great, will merge after fixed + new header image

2023-12-21 21:06 UTC, jobenjada commented on apps/formbricks-com/components/shared/AuthorBox.tsx
> +  src: string;
pls change variable name to something more telling e.g. imageSrc or photoSrc

2023-12-21 21:06 UTC, jobenjada commented on apps/formbricks-com/images/blog/ola-content-writer.jpg
legend!

2023-12-21 21:06 UTC, jobenjada commented on apps/formbricks-com/pages/blog/best-feedback-app-and-how-to-use-them/index.mdx
> +import Pendo from "./free-survey-tool-limesurvey-open-source-software-opensource.png";
"Pendo" but image name says its limesurvey

2023-12-21 21:06 UTC, jobenjada commented on apps/formbricks-com/pages/blog/best-feedback-app-and-how-to-use-them/index.mdx
> +    "Only when you understand your users and customers, they will come back and tell others about your service. ",
Please add more keywords here e.g. "We looked at the best in app feedback tools 2024 and found a clear winner. Gather feedback in your app for free with Formbricks."

2023-12-22 03:02 UTC, jobenjada commented
Hey @Olaleye-Blessing thanks for following up.

Two more things:

1. Please resolve this issue (I think its due to your changes in the writer avatar code)
<img width="956" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/cbfdf959-97aa-49c6-b4ee-4808086fa86b">

2. Please add a few more keywords to the names of these image files:
<img width="231" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/9d0e67b7-ccae-4392-a694-05ae6e316cd5">

you can see how I did it here:
<img width="392" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/df75a374-4671-4558-9906-b4304fdfe91c">

these keywords shouldnt be the same in each file, just write 4-6 into each file name related to the articles topic.

Thanks!!

2023-12-22 05:48 UTC, Olaleye-Blessing commented
Hello @jobenjada, you tagged the wrong person :-). I'm sure you wanted to tag @SiR-PENt :).

2023-12-22 20:28 UTC, SiR-PENt commented
@jobenjada, concerning the first issue, I think we have to find another way other than passing the `src` as prop. This will keep throwing this error as long as we make `imageSrc` a string in the `AuthorBoxProps` interface. 

I'm still trying to find my way around it though

2023-12-22 20:50 UTC, SiR-PENt commented
@jobenjada, I have added a temporary solution to this that will work just fine for both of us. Although, it might get cumbersome if there are more writers.

2023-12-22 22:13 UTC, jobenjada approved these changes

2023-12-22 22:30 UTC, merged