feat:
formbricks/formbricks pull request #2363
Opened 2024-03-29 12:23 UTC by gupta-piyush19

## What does this PR do?
Add response filtering for meta data

Fixes #2308 

## How should this be tested?

- Filter the responses based on the meta data fields

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2024-04-08 09:04 UTC, Dhruwang requested changes
Hey @gupta-piyush19 , looks good and filtering works super well 😊🚀

Here are some minor things that I noticed 

1. Double scroll bars

https://github.com/formbricks/formbricks/assets/67850763/15e9e5b7-e6eb-4022-8296-b8bf9ae5b083

2. Can we also change icon for action as # is already used for tags 
<img width="218" alt="Screenshot 2024-04-08 at 2 14 05 PM" src="https://github.com/formbricks/formbricks/assets/67850763/ade6e4af-eb9a-4ccc-b455-bf7f274c07e9">

3. Here can we rename the section for filtering languages from filter to something else (for example: Other filters) ?
<img width="494" alt="Screenshot 2024-04-08 at 2 15 54 PM" src="https://github.com/formbricks/formbricks/assets/67850763/9f3c01af-bb2d-4f7e-936f-6bfa770b130f">

4. Build errors 
![Screenshot 2024-04-08 at 2 33 34 PM](https://github.com/formbricks/formbricks/assets/67850763/fb6c4f78-12c5-42a4-bfec-c965acaf79a3)

Rest looks good ! 😊

2024-04-09 06:11 UTC, Dhruwang approved these changes
Good to go ! 🚀😊

2024-04-09 07:16 UTC, mattinannt requested changes
@gupta-piyush19 thanks; looks good overall :-) 
Can you please check why the e2e tests are failing and also add caching to the service :-)

2024-04-09 07:16 UTC, mattinannt commented on packages/lib/response/service.ts
> +export const getResponseMeta = async (surveyId: string): Promise<TSurveyMetaFieldFilter> => {
This service is not cached. Please add caching :-)

2024-04-09 08:46 UTC, gupta-piyush19 commented
Done with the changes, @mattinannt.
cc: @Dhruwang

2024-04-09 10:21 UTC, mattinannt approved these changes

2024-04-09 10:48 UTC, merged