feat: add survey schedule option
formbricks/formbricks pull request #2386
Opened 2024-04-03 16:10 UTC by mattinannt

## What does this PR do?

This PR adds the option to schedule a survey for a later so it gets published on the provided date automatically.
<img width="1161" alt="Screenshot 2024-04-03 at 18 05 59" src="https://github.com/formbricks/formbricks/assets/675065/8ac52292-35e2-4373-ac3f-0588e3b23149">

Fixes # (issue)

## How should this be tested?

- Create a new survey and set the new scheduling option in the response settings
- Once published, the survey should have the status `scheduled`.
- Change the `runOnDate` field in the survey manually to date in the past using prisma studio
- Run the cron job by calling the `/api/cron/survey-status` endpoint with a valid cron secret
```
curl --location --request POST 'http://localhost:3000/api/cron/survey-status' \
--header 'X-Api-Key: MY_SECRET'
```
- The survey should now be published

2024-04-04 09:09 UTC, jobenjada approved these changes
UI looks great! Didn't test the functionality so @gupta-piyush19 pls do so before merging :)

2024-04-08 06:39 UTC, gupta-piyush19 requested changes
Thanks, @mattinannt, for the feature; it works really well 🚀 
I just have a few suggestions related to code consistency; it would be great if you could comment on or fix them. 
Also, one more question: If a survey is already completed and I try to set the runOnDate, should it move to scheduled status or not? Currently, it's not.

2024-04-08 06:39 UTC, gupta-piyush19 commented on apps/web/app/api/cron/survey-status/route.ts
> +  const surveys = await prisma.survey.findMany({
can we rename the `surveys` variable to a more descriptive name, like `surveysToClose`

2024-04-08 06:39 UTC, gupta-piyush19 commented on .github/workflows/cron-closeOnDate.yml
can we rename this file to `cron-surveyStatusUpdate`? Also, please check in other CRON(s) to follow the same convention(name with spaces in the first line).

2024-04-08 06:39 UTC, gupta-piyush19 commented on docker/cronjobs
>  0 8 * * 1 curl $WEBAPP_URL/api/cron/weekly_summary -X POST -H 'content-type: application/json' -H 'x-api-key: '"$CRON_SECRET"''
Can we make it consistent to use either hyphen(-) or underscore(_)?
weekly_summary
close_survey -> survey-status

2024-04-08 07:02 UTC, mattinannt commented
@gupta-piyush19 Thanks for the review; I made the required changes; please take a look 😊

2024-04-08 09:21 UTC, gupta-piyush19 approved these changes

2024-04-08 09:41 UTC, merged