add: error handling to SDK
formbricks/formbricks pull request #240
Opened 2023-04-17 16:13 UTC by kymppi

Closes #231

2023-04-24 18:53 UTC, mattinannt requested changes
@kymppi thanks a lot for the PR 🤗 Makes total sense to add better error handling and really happy that you tackle this challenge.
I still encounter a few errors while testing. Can you please take a look at them and also rebase / merge the latest changes from main. E.g. I needed to change the init() flow to fix a few problems with one of our clients.
thanks a lot 🤗

2023-04-24 18:53 UTC, mattinannt commented on packages/js/src/lib/noCodeEvents.ts
>      default:
case falls through to error case. please add `break;`
(was missing before, I know)

2023-04-24 18:53 UTC, mattinannt commented on packages/js/src/lib/init.ts
> +    if (trackEventResult.ok !== true) return err(trackEventResult.error);
I'm getting the error
`TypeError: Cannot read properties of undefined (reading 'ok')`

2023-04-24 19:43 UTC, kymppi commented
**Important*': every function that returns the Result<T, E> type has to return one of these `ok(<value>)` `okVoid()` `err(<error>)`

2023-04-25 09:54 UTC, mattinannt commented
@kymppi Thanks for the changes 💪🎉 Looks great :-) 
I found two bugs and fixed them.
And I still have problems using the error handler. I added it to the init function but it's still the default error handler (logger) and I also can't find where it's set in the code.
<img width="571" alt="Screenshot 2023-04-25 at 11 51 45" src="https://user-images.githubusercontent.com/675065/234240934-e5a3f494-b3f2-4d15-8a5f-670614f15df2.png">
Also can you provide an object type for the `error` attribute. Since it's `any` I don't know if it's a real error object (with message attribute) or just a string.
If this is fixed I think we are ready to merge 💪

2023-04-25 10:05 UTC, kymppi commented
The default errorHandler is defined in config.ts, but currently its hard to add a type to the error since the errors are defined in the js package but the JsConfig and InitConfig types are from the types package

2023-04-25 16:08 UTC, kymppi commented
Okay, sorry for not testing it first. I'm currently rewriting how the error handler is initialized and how it is accessed 👍

2023-04-25 18:24 UTC, mattinannt approved these changes
thanks for the changes 💪 works great now 😊🚀🤗
I am going to merge it into main now. So it will go out with the next release probably tomorrow 😊🎉

2023-04-25 18:24 UTC, merged