Link survey mobile view
formbricks/formbricks pull request #2493
Opened 2024-04-19 09:17 UTC by Dhruwang

## What does this PR do?

Fixes https://github.com/formbricks/internal/issues/62

<img width="391" alt="Screenshot 2024-04-19 at 2 33 53 PM" src="https://github.com/formbricks/formbricks/assets/67850763/116cdb35-484c-4d94-96a0-2b504896acd7">

<img width="472" alt="Screenshot 2024-04-19 at 2 33 27 PM" src="https://github.com/formbricks/formbricks/assets/67850763/3adc6352-18b6-44fa-8b7a-b2c990008ab7">

It may break if you add too much content (long headline and description) in a question but it can be fixed with https://github.com/formbricks/formbricks/pull/2477

## How should this be tested?

Test link survey on small devices

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2024-04-22 07:12 UTC, jobenjada commented
Hey Dhru!

Thanks, looks good. However, if I test it on my iPhone, I have to scroll up to see the survey:

![IMG_2436](https://github.com/formbricks/formbricks/assets/72809645/e93ca020-94b4-4e38-97ec-d81d6a28dcf2)
![IMG_2437](https://github.com/formbricks/formbricks/assets/72809645/1c58ea84-3d44-4025-affd-2276633bc836)

Other than that, I like the filling out UX much better. Really easy within the thumb range :)

2024-04-22 07:12 UTC, jobenjada requested changes
see comment

2024-04-22 13:35 UTC, Dhruwang commented
Hey @jobenjada, Updated the PR 😊. For safari on mobile, there is an issue with the dynamic height of address bar, and due to which even though its `100vh`, it still scrolls because address bar at the bottom takes some height

2024-04-23 15:14 UTC, jobenjada requested changes
Hey Dhru!

Noticed two more things:

The bottom border corners shouldn't be rounded on mobile:

<img width="465" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/cbd50a35-675a-443a-8c56-97028ed24e6e">

Secondly, we currently have uneven paddings for top and bottom (`pt-6` and `pb-3`) which is good for Desktop and in-app. 

On mobile, pls sync them so its `pt-6` and `pb-6`

So should look like this:

<img width="509" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/0193b8f9-872b-4a4f-a88f-930ed9f57830">

Thanks a lot! :)

2024-04-23 15:14 UTC, jobenjada commented on packages/ui/Survey/index.tsx
> -  return <div id={containerId} className="h-full w-full" />;
did you test this well? Feels like it'd break the layout in other places ;)

2024-04-24 12:32 UTC, Dhruwang commented
Hey @jobenjada , have updated the PR 😊
![Screenshot 2024-04-24 at 6 00 33 PM](https://github.com/formbricks/formbricks/assets/67850763/cfd0d637-3523-4d4b-aee4-aaa9a1c2d4ba)

2024-04-24 14:14 UTC, merged