feat: replaces dnd with dnd-kit
formbricks/formbricks pull request #2564
Opened 2024-05-01 14:40 UTC by pandeymangg

## What does this PR do?

Replaces the current library `react-beautiful-dnd` which is used for dnd with [@formkit/drag-and-drop](https://drag-and-drop.formkit.com/)

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-05-02 07:45 UTC, jobenjada requested changes
Hey! :) 

Looks good, but I broke it quite quickly:

<img width="1049" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/a80f6d45-0c37-4c1c-a111-5c82f2b3b17d">


1. Added a new question
2. Dragged the open card to the top

https://github.com/formbricks/formbricks/assets/72809645/46f656cb-f18b-4f31-ab82-75e552083d9c

--------

2. Just a small thing but I find it confusing that the the number of the card I grab does not change but its replica changes the number:

https://github.com/formbricks/formbricks/assets/72809645/a6cf1a50-7c29-4fb5-87ce-3687229313bc

A solution could be to blur / hide the number of the card you drag? Not sure how the DnD works so open for your suggestion 🤓 

------

Also one E2E test failed previously

2024-05-06 09:21 UTC, mattinannt requested changes
Shared a video via Slack. Unfortunately it's not working in my local environment

2024-05-13 15:10 UTC, mattinannt requested changes
@pandeymangg Looks great :-) 
Only two small things I noticed while using it:

Can we also make the whole slate area drag-able to make it easier for people to drag and pull instead of only the 9 dots? :-) 
<img width="330" alt="Screenshot 2024-05-13 at 17 06 43" src="https://github.com/formbricks/formbricks/assets/675065/2ae686e1-840c-4066-bbe0-5d6fb386b982">

Also when we drag a choice we get overlapping borders. Can we give the input a background color to avoid this? :-) 
<img width="435" alt="Screenshot 2024-05-13 at 17 08 37" src="https://github.com/formbricks/formbricks/assets/675065/47541985-c058-4f8c-abec-ae8fdfc4d963">

2024-05-14 08:25 UTC, mattinannt approved these changes

2024-05-14 12:01 UTC, merged