feat: Extend Prefilling with an option to auto-skip prefilled values
formbricks/formbricks pull request #2598
Opened 2024-05-09 13:54 UTC by gupta-piyush19

## What does this PR do?
Extend Prefilling with an option to auto-skip prefilled values.

Fixes 
https://github.com/formbricks/internal/issues/145

## How should this be tested?
- Test the functionality of multi-ques prefilling with a new query param `skipPrefilled=1`.
- It should skip the prefilled questions

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2024-05-13 11:07 UTC, pandeymangg requested changes
Thanks a lot for the PR! @gupta-piyush19 😊 
Looks good, just left some comments for minor refactor, pls take a look 🙏

2024-05-13 11:07 UTC, pandeymangg commented on apps/web/app/s/[surveyId]/components/LinkSurvey.tsx
> +          isInEditor={false}
Please rename this prop to something like `isResetProgress` as it conveys better about what this does, and is a boolean

2024-05-14 02:49 UTC, pandeymangg approved these changes
Thanks a lot for the changes! 
LGTM! 🚀

2024-05-23 10:43 UTC, mattinannt approved these changes
@gupta-piyush19 Nice, the feature works great!! :-) 💪
I only changed the value of `skipPrefilling` from `1` to `true` since I noticed we now also use `true` in all other functionality and this felt more consistent with the other features.
Great job; let's merge this :-)

2024-05-23 11:48 UTC, merged