feat:  recall from hidden fields and attributes
formbricks/formbricks pull request #2601
Opened 2024-05-10 06:42 UTC by Dhruwang

## What does this PR do?

Fixes #2353 #2327 

- Now we also allow recalling from hidden fields and attributes
- Initially it was mainly focused on question, so we used namings like `recallQuestion`, `selectRecallQuestion` but now its more generic, so now we use `recallItem`, `selectRecallItems`

Attributes

<img width="332" alt="Screenshot 2024-05-10 at 12 02 34 PM" src="https://github.com/formbricks/formbricks/assets/67850763/1b80daf4-dadb-48e6-8075-ff99ed28416f">

Hidden Fields 

<img width="580" alt="Screenshot 2024-05-10 at 12 01 36 PM" src="https://github.com/formbricks/formbricks/assets/67850763/6e90fc4f-b937-4c5d-bb6a-47bd918a8f08">

Also made the recall object more expandable to support other fields in future

## How should this be tested?

For link surveys -> recall from questions and hidden fields is allowed
Fo app surveys -> recall from questions and attributes is allowed

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2024-05-10 13:46 UTC, jobenjada commented
hey @Dhruwang 

thanks a lot, love how you always crank out a bunch of cool improvements out on a given day :D 🚀 

Here's what I noticed:

1. If the @ is the first character in the input, I cannot select the option:

<img width="330" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/8040f0d0-c564-4d89-8d07-7ecf38f5a352">

-------

2. We need to make clear that the second input field is the placeholder for the second recall item:

<img width="400" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/406a563e-65e5-4442-a2b3-166cd0db0aa8">

Easiest would be to add a placeholder text with the recall item label so the hiddenField id or the question.

-------

3. The recall of attributes does not seem to work for me. I've recorded a video to show how I tried:

https://github.com/formbricks/formbricks/assets/72809645/636b8dc9-e0b6-43e5-a87e-d48d3345f716

-------

4. Kombobox / Search bar for dropdown: some users have thousands of attributes. It would make sense to add the same combobox that we're now using in the Logic Editor:

see here: https://github.com/formbricks/formbricks/pull/2584

-------

Did you try your implementation with each question types? I normally find bugs when I do that 😉

-----

Other than that, it works great :) Thanks!

2024-05-13 07:30 UTC, Dhruwang commented
Hey @jobenjada , have updated the PR ! 😊

Fallback input with placeholders 

<img width="425" alt="Screenshot 2024-05-13 at 12 52 18 PM" src="https://github.com/formbricks/formbricks/assets/67850763/c9673d3f-7c12-40b5-850a-09bec5aefa95">

Searchable dropdown

<img width="449" alt="Screenshot 2024-05-13 at 12 21 25 PM" src="https://github.com/formbricks/formbricks/assets/67850763/64ad26b4-db7a-4f37-b8cc-06d406730caa">


Also tested the recall from attributes and it seems to work fine 🤔

https://github.com/formbricks/formbricks/assets/67850763/57c8d8fa-ea2c-41be-9965-535590e129f2


In the video that you provided, did you miss the survey saving ?

2024-05-13 09:06 UTC, jobenjada commented
Hey Dru!

Looks good :)  Here's my feedback:

1. Keyboard usability

With the search bar, we lost keyboard usability: 
<img width="445" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/0285005d-ac99-495e-aadc-233768332eee">

Pls make sure that `Arrow down` lets people select one of the fields. Similarly, if they go back up with the keys they should hop back into the Search bar once they reach the top of the list.

-------

2. UI changes in response card

As laid out in Slack

------

Please ping me once you've reworked the attribute logic, then I'll test it.

Thanks!

2024-05-13 15:37 UTC, jobenjada approved these changes
looks great! :)

2024-05-27 06:25 UTC, pandeymangg requested changes
Hey @Dhruwang thanks for the PR, looks great 🚀 
I just had one issue with it that I've written, pls take a look at it. And also make the changes to `recallToHeadline` function and the `ee` service as we discussed 😊

2024-05-27 06:25 UTC, pandeymangg commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryPage.tsx
>    survey = useMemo(() => {
Please don't mutate the function parameter `survey`, you can make a new variable here `surveyMemoized` and use it in the rest of the places 😊 

```
const surveyMemoized = useMemo(() => {
    return checkForRecallInHeadline(survey, "default", attributeClasses);
  }, [survey, attributeClasses]);
```

2024-05-27 15:04 UTC, mattinannt commented on apps/web/app/api/v1/client/[environmentId]/app/sync/lib/utils.ts
> +export const checkForAttributeRecall = (survey: TSurvey, attributes: TAttributes): TSurvey => {
I would assume that a `check...' method would return true or false, but this function modifies the survey and returns the modified one. So maybe something like `replaceAttributeRecalls()` would be more appropriate?
(still not sold on it, but maybe in that direction)

2024-05-27 15:20 UTC, mattinannt approved these changes
@Dhruwang thanks for the PR :-) Looks great! 💪

I like the approach of referencing attributes especially since we are now moving into a more person-centric direction.
I would also love to have this feature for link surveys and will write a ticket for it :-)

2024-05-27 15:40 UTC, merged