fix: multi and single select questions
formbricks/formbricks pull request #2606
Opened 2024-05-10 12:06 UTC by pandeymangg

## What does this PR do?
Makes a common component for the `MultipleChoiceMulti` and `MultipleChoiceSingle` select questions called `SelectQuestion`. The types for both the questions types were also almost the same, only the logic had a difference, which is now being solved with `zod.refine`

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-05-13 09:51 UTC, gupta-piyush19 requested changes
Thanks, @pandeymangg, for the changes 😊 
I've added a few comments 🙂 
Please make the changes accordingly 🙏

2024-05-13 09:51 UTC, gupta-piyush19 commented on packages/types/surveys.ts
> +    }
please write comments in English only 😊

2024-05-13 09:51 UTC, gupta-piyush19 commented on packages/database/data-migrations/20240318050527_add_languages_and_survey_languages/lib/i18n.ts
> +    // } else return ZSurveyMultipleChoiceMultiQuestion.parse(clonedQuestion);
please remove the comments.

2024-05-13 09:51 UTC, gupta-piyush19 commented on apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SelectQuestionForm.tsx
>                Convert to Multi Select
Please modify this button to change the type of the question(single to multi and vice versa).

2024-05-13 10:26 UTC, gupta-piyush19 approved these changes

2024-05-13 10:29 UTC, gupta-piyush19 commented
LGTM 🚀 
Thanks, @pandeymangg  🙌

2024-05-13 14:54 UTC, mattinannt requested changes
@pandeymangg thanks for the PR :-) Looks good, the only thing I'm not so happy with is the naming. I would like to keep the term `MultipleChoice` instead of `Select` since we still have the two different question types `multipleChoiceSingle` & `multipleChoiceMulti`. Combining them in one form for me the name `MultipleChoiceQuestionForm` feels more consistent.

Please make the changes; then we are ready to merge this :-)

2024-05-14 08:26 UTC, mattinannt approved these changes

2024-05-14 08:37 UTC, merged