feat: rework loading in Settings pages
formbricks/formbricks pull request #2650
Opened 2024-05-18 00:47 UTC by beonma

## What does this PR do?

This pull request ensures that the skeleton is correctly loaded into the appropriate shapes on all settings pages.

Fixes #2620

![Screenshot from 2024-05-18 01-26-25](https://github.com/formbricks/formbricks/assets/77807053/ccc04599-f68d-48a3-b922-3f88b7e6d9f3)
![Screenshot from 2024-05-18 00-04-06](https://github.com/formbricks/formbricks/assets/77807053/06d6a124-ad6e-47c3-9a42-81ecbb4b5c70)
![Screenshot from 2024-05-18 00-04-12](https://github.com/formbricks/formbricks/assets/77807053/d538205a-4289-4eb5-ad61-b63bc36093a0)

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-05-18 00:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/formbricks/formbricks?pullRequest=2650) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/formbricks/formbricks?pullRequest=2650) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/formbricks/formbricks?pullRequest=2650) it.</sub>

2024-05-23 04:32 UTC, gupta-piyush19 requested changes
Thanks, @beonma, for the fix. 😊 
Changes look good and consistent with the codebase. There is just one loading behavior that seems a bit off, can you please check the comments and fix this? 
We'll be good to go after that 🚀

2024-05-23 04:32 UTC, gupta-piyush19 commented on apps/web/app/(app)/environments/[environmentId]/settings/(team)/enterprise/loading.tsx
> +};
Please remove the unused code.

2024-05-23 04:32 UTC, gupta-piyush19 commented on apps/web/app/(app)/environments/[environmentId]/settings/(team)/members/loading.tsx
Can you please try fixing these two loading behavior? It first shows the loading element and then the loader for the table, it would be great to see something consistent in just one loader.

https://github.com/formbricks/formbricks/assets/56182734/52b245f7-8c0b-42fe-a68d-cf4966790ceb

2024-05-24 02:58 UTC, beonma commented on apps/web/app/(app)/environments/[environmentId]/settings/(team)/members/loading.tsx
Hi, @gupta-piyush19.
I encountered difficulty in reproducing this issue, as I am using the local version with Docker (i guess). Despite removing the cache function to potentially observe the loading, I was still unable to replicate the problem. I have implemented some additional code to ensure consistency in appearance. Please feel free to request any further modifications.

2024-05-24 16:09 UTC, beonma commented
Hi @gupta-piyush19, I have made the necessary changes, along with some additional adjustments for UI consistency. Please let me know if anything else needs to be modified.

2024-05-29 06:04 UTC, gupta-piyush19 commented
> Hi @gupta-piyush19, I have made the necessary changes, along with some additional adjustments for UI consistency. Please let me know if anything else needs to be modified.

Thanks @beonma for the changes 👍
LGTM, we can now merge this 🚀 😊

2024-05-29 06:06 UTC, gupta-piyush19 commented
@pandeymangg Can you please take a final look at the code changes, as these files were recently edited? 😊

2024-05-29 07:51 UTC, pandeymangg commented
Hey! @beonma the changes look good for the settings pages, except the `settings/billing` page which still seems to have a wrong loading UI, could you also pls take a look at it? 😊 

https://github.com/formbricks/formbricks/assets/54475686/1064be29-2f8c-48df-be1c-647bf812afc1

2024-05-31 02:45 UTC, beonma commented
Hey, @pandeymangg.
I've made the necessary adjustments to the billing page. Please review the changes to ensure they meet the desired output. Feel free to suggest any additional modifications if needed.

Is there a way to simulate the cloud version within a local development environment? Because i overlooked these parts of the code due to working solely with the community version.

2024-06-03 05:04 UTC, pandeymangg commented
> Hey, @pandeymangg. I've made the necessary adjustments to the billing page. Please review the changes to ensure they meet the desired output. Feel free to suggest any additional modifications if needed.
> 
> Is there a way to simulate the cloud version within a local development environment? Because i overlooked these parts of the code due to working solely with the community version.

Thanks for making the changes! looking good now 😊 
and to simulate the cloud version you can set `IS_FORMBRICKS_CLOUD=1` in your .env file

2024-06-03 15:07 UTC, pandeymangg approved these changes
LGTM! 🚀

2024-06-03 15:17 UTC, beonma commented
Thank you @pandeymangg ! Thanks @gupta-piyush19 for reviewing this pr too.

2024-06-03 15:35 UTC, merged