feat: Filter Responses by hidden field values
formbricks/formbricks pull request #2662
Opened 2024-05-21 09:15 UTC by gupta-piyush19

## What does this PR do?
- Filter Responses by hidden field values
- Adds response filtering on hidden fields

Fixes:
https://github.com/formbricks/internal/issues/171

## How should this be tested?
- Create a survey with hidden fields in it
- Fill out the survey with hidden fields values
- filter the responses on the summary/response page

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-05-29 09:07 UTC, pandeymangg requested changes
Thanks for the PR @gupta-piyush19 looks great 🚀 
just mentioned two small things, pls have a look 😊

2024-05-29 09:07 UTC, pandeymangg commented on apps/web/app/lib/surveys/surveys.ts
> +  const [questions, tags, attributes, others, meta, hiddenFields] = selectedFilter.filter.reduce(
pls use a `map` here instead of a reduce, it fits the use case better 😊

2024-05-29 09:49 UTC, pandeymangg approved these changes
LGTM! 🎸

2024-05-30 11:00 UTC, mattinannt approved these changes
@gupta-piyush19 thanks for making the changes :-) Looks great! 💪

2024-05-30 11:11 UTC, merged