feat: Revamp No-Code Action Form
formbricks/formbricks pull request #2688
Opened 2024-05-25 19:10 UTC by gupta-piyush19

⚠️ Data migration:
⚠️ E2e tests fixture(90% done)
⚠️ Docs update

@mattinannt

## What does this PR do?
- Revamp No-Code Action Form
- Automatic actions except New sessions are of type noCodeActions

Fixes 
https://github.com/formbricks/internal/issues/193

## How should this be tested?

- Create new actions using the new form
- Test the new actions in the demo app, with new specific URL support for all the noCode actions.

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-06-04 10:57 UTC, pandeymangg requested changes
Thanks for the changes @gupta-piyush19 looks great 🚀 
Please change the no code action logic in the js package to use common functions like earlier, I already looked at the data migration and it looks good as well, did some changes in the react hook form implementation as well, please do this and this will be ready after a final round of testing 😊

2024-06-05 06:08 UTC, pandeymangg approved these changes
LGTM! 🚀

2024-06-05 10:25 UTC, mattinannt requested changes

2024-06-05 10:26 UTC, mattinannt commented on packages/database/package.json
> +    "data-migration:extended-noCode-Actions": "ts-node ./data-migrations/20240524053239_extends_no_code_action_schema/data-migration.ts"
solved :-)

2024-06-10 16:36 UTC, mattinannt approved these changes
@gupta-piyush19 thanks for making the changes; works great! 😊🚀
Ready to be merged :-)

2024-06-10 20:41 UTC, merged