fix: settings forms
formbricks/formbricks pull request #2700
Opened 2024-05-28 11:42 UTC by pandeymangg

## What does this PR do?

refactors the profile name, profile avatar and organization name forms to react hook form

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-05-29 05:34 UTC, gupta-piyush19 requested changes
Thanks, @pandeymangg, for the changes 🙌 
Working as expected 🚀 
I've added a few review comments to fix, mostly related to optimisation and code consistency. Can you please take a look at it? 😊

2024-05-29 05:34 UTC, gupta-piyush19 commented on apps/web/app/(app)/environments/[environmentId]/settings/(account)/profile/components/EditProfileDetailsForm.tsx
> +      const nameTrimmed = data.name.trim();
Can we please rename this to name instead, it would be more consistent.

2024-05-29 06:55 UTC, pandeymangg commented on apps/web/app/(app)/environments/[environmentId]/settings/(account)/profile/components/EditProfileAvatarForm.tsx
> +                    }}>
is there any benefits to using that other than refs?

2024-05-29 08:48 UTC, gupta-piyush19 commented
Thanks @pandeymangg for the changes 🙌 
LGTM! 🚀

2024-05-29 08:54 UTC, gupta-piyush19 approved these changes

2024-05-29 13:01 UTC, mattinannt requested changes
@pandeymangg thanks for the PR, looks good, only a small concern regarding the user type:

2024-06-03 14:40 UTC, mattinannt approved these changes
@pandeymangg thanks for making the changes :-) Looks great! 🚀
Let's hope the prisma migration goes through 🤞

2024-06-03 14:55 UTC, mattinannt commented
@pandeymangg Looks like we are stuck on some build errors. Can you please take a look? 👀 :-)

2024-06-03 15:37 UTC, merged