fix: survey editor validation
formbricks/formbricks pull request #2749
Opened 2024-06-10 16:24 UTC by pandeymangg

## What does this PR do?

Fixes survey editor validation with zod refinements as the center-piece

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-07-04 15:30 UTC, gupta-piyush19 requested changes
Thanks, @pandeymangg, for the PR. 🙌 
Survey editor works great, and the changes look good.
I've added a few comments. Can you please check them out? 🤓 
I'm still testing  and will add more comments in case of any issues in the functionality

2024-07-04 15:30 UTC, gupta-piyush19 commented on packages/types/surveys/types.ts
> +          : initialFieldsToValidate;
can you please simplify this piece of code with
``` ts
    const initialFieldsToValidate = [
        "html",
        "buttonLabel",
        "upperLabel",
        "lowerLabel",
        "label",
        "placeholder",
      ];

      const fieldsToValidate =
        questionIndex === 0 ? initialFieldsToValidate : [...initialFieldsToValidate, "backButtonLabel"];```

2024-07-04 15:30 UTC, gupta-piyush19 commented on packages/types/surveys/types.ts
> +  .superRefine((survey, ctx) => {
Please add a few comments in the superRefine handle where you think clarification is necessary.

2024-07-04 15:41 UTC, gupta-piyush19 commented
A few more comments:
1. Please fix build errors, unit and e2e tests.
2.  ![image](https://github.com/formbricks/formbricks/assets/56182734/4268bc65-c359-400c-8e75-379a4b944f97) I can save the website survey without selecting any survey trigger.
3. ![image](https://github.com/formbricks/formbricks/assets/56182734/6712e81c-1fa4-40b6-bc26-4e56b2d5ffbf) - Getting generic error in case of empty inputs, can we add the config name to add more context in the error message?
4. ![image](https://github.com/formbricks/formbricks/assets/56182734/bd3085fe-62e5-4c9e-8bfb-431a55476721) - casing looks a bit off, take help from @jobenjada to find out the best error message 🤓 
Thanks 🙏

2024-07-05 09:49 UTC, gupta-piyush19 commented
Thanks @pandeymangg, for the changes 🙌 
LGTM 🚀 
@jobenjada, Can you please test the UI/UX of the survey editor and suggest some error messages? 🤓

2024-07-05 09:49 UTC, gupta-piyush19 approved these changes

2024-07-06 07:33 UTC, jobenjada requested changes
Hey Pandeyman,

this looks really good, thanks for your work!! 💪 

Regarding UX I have a few points:

1. Align field names with UI labels: There is a mismatch between the name of the field and the label of the input field:

subheader vs. Description
<img width="884" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d9941a37-40d0-4938-a88a-35dcd8fd0142">

headline vs. Question 
<img width="943" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/b74dfe63-648c-4933-b5d3-d3533fb11928">

<img width="432" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/d2641613-7112-481c-8b47-41c21f530bd3">

<img width="317" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c4a509cf-3bc0-45bf-a0c0-9c39717b5f6f">


---------

2. Capitalize the first word in all error messages: If error messages start with a variable, they're not capitalized. I found a work around by adding "The" which I also find to be more user-friendly:

<img width="218" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/882e0ba8-ff6e-4ee4-98b7-70c5ba372c9a">

I'm not sure if I have caught all cases with all error messages, please double check an either add an article or capitalize the variable.

--------

4. The error messages are written from a code perspective, not form a user perspective. For example: "The headline in question 1 is not valid for the following languages: Abkhazian"

What does "not valid" mean? I see that there are two cases: "invalid" and "not valid for languages"

Does it just mean they are missing? Ideally, we'd reframe the error message to an information the user can act on. If we say its "missing:, they know they have to add it. If we say its "invalid" the user doesn't know how to validate it. 

------

5. Cyclic Logic: Is logic which jumps to a question ahead of the question where the logic is set always cyclic? If so, why don't we filter out the questions from the select list?

------

Not sure if I've found all of the error messages ;) ping me if I missed some 

Thanks! 🤙

2024-07-09 13:33 UTC, mattinannt approved these changes
@pandeymangg Works great!! 💪
Thanks a lot for this revamp; it really improves the survey editor and makes sure we validate everything and can point to what information is missing or in the wrong format 💪🚀

2024-07-09 14:44 UTC, merged