feat:  multiple end screens
formbricks/formbricks pull request #2863
Opened 2024-07-09 14:57 UTC by Dhruwang

## What does this PR do?

Fixes https://github.com/formbricks/internal/issues/269

Add ability to create multiple endings (endScreen or redirectToUrl)
Also contains a data migration to migrate all the existing thankyou cards endings

## How should this be tested?

<img width="841" alt="Screenshot 2024-07-09 at 8 26 35 PM" src="https://github.com/formbricks/formbricks/assets/67850763/0d92af65-11aa-4fc3-a6a8-e8530a36308c">
<img width="841" alt="Screenshot 2024-07-09 at 8 26 44 PM" src="https://github.com/formbricks/formbricks/assets/67850763/3430cd10-de8b-4473-856b-5c94d1433211">
<img width="831" alt="Screenshot 2024-07-09 at 8 26 26 PM" src="https://github.com/formbricks/formbricks/assets/67850763/7a04ce53-0763-4486-8279-97878731ebdc">

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2024-07-15 09:25 UTC, mattinannt requested changes
@Dhruwang thank you for the PR 😊 It works great already 🚀, but there are still a few points we need to improve:

- Redirect Url should only be on the paid plan (at least Startup plan) for Formbricks Cloud and should be in the community edition for self-hosters. Running this locally with `IS_FORMBRICKS_CLOUD` disable I still get the following limitations even though the feature should be available:

<img width="1144" alt="Screenshot 2024-07-15 at 10 34 45" src="https://github.com/user-attachments/assets/a2010ef5-7f7e-4bb0-ab13-59d279cf83d6">

- When only one thank you card is created or shown, the `Delete` button (trash icon) should still be visible but disabled. In App/Website surveys also the last ending can be deleted.
<img width="617" alt="Screenshot 2024-07-15 at 10 43 55" src="https://github.com/user-attachments/assets/bba73352-4672-4f1f-bc75-8577e461133d">

- trying to upload a title image for a thank you card throws this error:
<img width="1135" alt="Screenshot 2024-07-15 at 10 46 25" src="https://github.com/user-attachments/assets/46258438-1d98-4431-aaf7-71518c6c489f">

- The label for the redirect card shouldn't be optional. It should not be possible to save a survey without setting the label to avoid inconsistent data.
<img width="406" alt="Screenshot 2024-07-15 at 10 54 52" src="https://github.com/user-attachments/assets/8fcfac71-29c2-4ec1-a8ec-5ed44eda3d18">

- Recall: Can we activate recall for the url to enable dynamic redirect URLs?
<img width="611" alt="Screenshot 2024-07-15 at 10 56 37" src="https://github.com/user-attachments/assets/94024b7e-2380-45c8-8c76-933f90390e24">

- Toggle & Navigation: The UI/UX for endings should be the same as with questions. Users should be able to duplicate endings and access the context menu (without changing the question type). For consistency we also remove the `Show` toggle as it's now possible to delete/add new endings and we don't need this anymore (this was a flaw in the concept, sorry about that)
Please make sure to use reusable components for questions and endings where it makes sense.

- Strange re-swapping behaviour: Even though changing the order works with drag and drop it looks like it doesn't since after releasing the card it goes back to it's original place (but the content changes). Please fix so it's staying in the place where it's dropped at.

https://github.com/user-attachments/assets/669e870b-a0e0-4cce-981c-cc0af333dae8

- Inconsistent behaviour in Tabs: The "End Screen" tab seems to keep the state/inputs when switching tabs and the "Redirect to URL" tab don't. Make sure to keep the state in the editor so the user can switch back and forth while editing but as soon as the changes are saved the not needed part is pruned. A survey in the database shouldn't have the type `endScreen` but a `redirectUrl` at the same time. Ideally this can be done (and validated) using zod.

https://github.com/user-attachments/assets/384bda96-0abb-4adf-a96e-e3c5fbed04c9

2024-07-15 09:25 UTC, mattinannt commented on apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SurveyMenuBar.tsx
> +      console.log(currentError.path);
please remove console log

2024-07-15 09:25 UTC, mattinannt commented on apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/lib/minimalSurvey.ts
> +      id: "end:1",
please use cuid2 as IDs like we do it in the questions.

2024-07-15 09:25 UTC, mattinannt commented on package.json
> +      "prettier --write"
please revert change

2024-07-15 09:25 UTC, mattinannt commented on packages/surveys/src/components/general/EndingCard.tsx
> +      window.location.replace(endingCard.buttonLink);
does this also needs to be `window.top?.location.replace()`?

2024-07-15 09:25 UTC, mattinannt commented on packages/database/schema.prisma
> +  endings            Json[]           @default([])
please move `endings` up below the `questions` so also in prisma studio this shows after the questions which makes it easier to manually make changes to records.

2024-07-30 20:32 UTC, jobenjada commented
Looks and feels a lot nicer and cleaner :)

Left a comment on Slack regarding pot. refactoring of the very large EditEndingCard.tsx

Other than that, ready for review @mattinannt !

2024-08-01 14:06 UTC, mattinannt approved these changes
🚀 Ready to merge 🥳

2024-08-02 04:52 UTC, merged