feat: add storybook for Label component
formbricks/formbricks pull request #2907
Opened 2024-07-17 10:05 UTC by Trjindal

## What does this PR do?

Adds Label component to storybook

Fixes # (issue)

https://github.com/user-attachments/assets/163f3e5d-3a6c-49ea-9689-664934136673

## How should this be tested?

-Run Storybook using` pnpm storybook`
- Inspect Storybook on `http://localhost:6006/`
## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-07-19 15:10 UTC, gupta-piyush19 requested changes
Thanks, @Trjindal, for the storybook feature. 😊 
change looks good and works great 🚀 
I've added a few small comments. Can you please fix them? Please fix them in your other PRs as well.
Thanks 🙌

2024-07-19 15:10 UTC, gupta-piyush19 commented on packages/ui/Label/stories.tsx
> +const meta: Meta<typeof Label> = {
Please use the consistent approach to type things; other component's stories use `satisfies` to type the meta. Can you please make it the same here?

2024-07-19 15:10 UTC, gupta-piyush19 commented on packages/ui/Label/stories.tsx
> +  title: "UI/Label",
set the title as `ui/Label`, again consistency 😅

2024-07-19 15:10 UTC, gupta-piyush19 commented on packages/ui/Label/stories.tsx
> +The **Label** component is used to label form fields in your application.
The **Label** component is used to label the form fields.

Can you please update the description? Also, please add a description in other existing stories as well. 😊

2024-07-20 09:44 UTC, Trjindal commented on packages/ui/Label/stories.tsx
> +// src/Label.stories.tsx
Hi Piyush all the requested changes are done . please take a look. 😊

2024-07-26 05:03 UTC, gupta-piyush19 approved these changes
Thanks @Trjindal for the changes 😊 
LGTM 🚀

2024-07-31 08:01 UTC, mattinannt commented
/award 50

2024-07-31 08:14 UTC, merged