feat: Advanced logic editor
formbricks/formbricks pull request #3020
Opened 2024-08-19 07:49 UTC by gupta-piyush19

## What does this PR do?
Advanced logic editor

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-08-29 10:35 UTC, jobenjada commented
hey Piyush, I'll pre-review this to save us a feedback loop 🤓 

It's looking great already! Here's what I noticed?

1. Let's move this inside of the last block of Conditional Logic. Some users created logic for all options because they didn't see it. If it sits inside the gray box, it should be clearer. Also, make sure the font size and color is the same like the "When" and "Then" texts in the gray container:
<img width="389" alt="image" src="https://github.com/user-attachments/assets/5132d96d-9c0d-4888-9ed1-b0ec4533aaf9">

2. Text size: The rest of the surey editor is `sm` so please change all of the texts to sm within the logic editor
<img width="626" alt="image" src="https://github.com/user-attachments/assets/583c634f-b891-4f38-8881-afc59104142e">

2.b. Icon size and color: These icons can be a bit smaller and darker for better usability
<img width="41" alt="image" src="https://github.com/user-attachments/assets/f80b15b1-7b4e-4160-9037-84ede91a5f28">

3. Keep spacing between input fields consistent: In the conditions its too wide, in the actions too narrow. Maybe `gap-x-2` should work
<img width="172" alt="image" src="https://github.com/user-attachments/assets/81f2cfe3-88bd-4081-b3a6-faf276d7a2fe">

also gap here is too wide and inconsistent with gap between Condition and Action
<img width="337" alt="image" src="https://github.com/user-attachments/assets/432f1644-190f-4788-82c4-c18050e78403">

I think you can get rid of `mt-2` here
<img width="381" alt="image" src="https://github.com/user-attachments/assets/4a43fdb1-c016-4a71-afd7-855088c7740b">

4. hover:cursor-pointer
<img width="215" alt="image" src="https://github.com/user-attachments/assets/ba9bb2d9-0781-4c37-9850-fc67c4e64b38">

5. Remove the outer gray container: It's clear enough and gives us some space
<img width="631" alt="image" src="https://github.com/user-attachments/assets/5bd9691f-db4b-4939-82b9-d2e02d1c8f4f">

6. Replace Emoji with lucide `file-digit`
<img width="176" alt="image" src="https://github.com/user-attachments/assets/b0d51a65-2f57-45ac-876a-9e5d6ce9449a">

here as well:
<img width="239" alt="image" src="https://github.com/user-attachments/assets/711912ca-900a-4fbc-b51f-d5c0118c6558">

7. Tweak Combobox UI: border-r not rounded if item selected
<img width="221" alt="image" src="https://github.com/user-attachments/assets/b125c27f-e89b-419f-a177-9e54ddee4f65">

and there is a double border separating the input from the dropdown
<img width="178" alt="image" src="https://github.com/user-attachments/assets/0209bec7-8499-49e3-9c27-fc71a69f573a">

8. Spacing: Remove top padding
<img width="232" alt="image" src="https://github.com/user-attachments/assets/e6683d0f-9bbe-4c10-b27d-fefd403be996">

8.b. This icon needs more space on the right:
<img width="103" alt="image" src="https://github.com/user-attachments/assets/62f3c3c2-44eb-47fc-8da6-6488a09c276c">


9. Logic block: Since they are executed in sync, we need to allow resorting them. Replace delete icon with context menu for logic block with: Duplicate, Move Up, Move Down, and Delete. Add the icons we use for this functionality on Question Cards
<img width="229" alt="image" src="https://github.com/user-attachments/assets/8ca51113-88d5-4969-834a-7d8a2cd53bcf">

10 Update Delete icon to match rest of survey editor:
<img width="234" alt="image" src="https://github.com/user-attachments/assets/dc8a6485-20df-4f01-92ff-aa6fa412aaa0">

vs

<img width="112" alt="image" src="https://github.com/user-attachments/assets/37de2ab1-bc94-4f0f-8ab6-e8d32bd66be2">

11.  I think this needs to get filtered out? Not sure if that makes sense
<img width="444" alt="image" src="https://github.com/user-attachments/assets/70d889dd-f402-498a-bf27-eed92940c1ff">

That's it in terms of UI / UX. I'll do a proper test when you've marked the PR ready for review 🤓 

**Thanks, great work!!**

2024-09-06 07:16 UTC, jobenjada commented
Please make sure to add the variables to the response data (exports, integrations, etc)

2024-09-10 09:36 UTC, Dhruwang requested changes
Hey @gupta-piyush19 , tested the logic functionality, overall works well 🚀🙌🏻

Here are some issues that i noticed.

### Modifying logic operator in open text question does not work 

Steps to reproduce  

1. Add a logic to an open text question 
2. Change operator (for example change `equals` to `does not equal`)

Noticed the same issue in date question (please check for other questions as well)  

https://github.com/user-attachments/assets/f25414c7-0a3f-48d9-b1b4-303952385b0b

<img width="1725" alt="Screenshot 2024-09-10 at 2 14 22 PM" src="https://github.com/user-attachments/assets/5ac9d863-745b-423a-9e5f-e549d83c537b">

 
 
### Cannot save survey with logic where optional question is logically set to require
 
Steps to reproduce 
1. Add a logic to a question where action is `Require Answer` 
2. Select an optional question from the dropdown 
3. Try to save the survey    


https://github.com/user-attachments/assets/5dd4b4f6-58f3-4aa7-bfe4-f752941dcd6c



### Questions in operand dropdown 

In SS, it can be seen that for open text questions, operand input is a dropdown. So is it also possible to compare value of current question with answer of those question included in the dropdown?  or that dropdown should not contain questions  🤔
<img width="794" alt="Screenshot 2024-09-10 at 10 10 25 AM" src="https://github.com/user-attachments/assets/9010fdbe-159b-440e-a398-90d19e8ec215">


### Fix alignment of icon on variables card 
<img width="527" alt="Screenshot 2024-09-10 at 10 30 17 AM" src="https://github.com/user-attachments/assets/a40d8102-eaf9-4d3d-8cd4-7a8c2e5efefd">



### Jumps based on variable values does not work  

As you can see in the video below, I have a variable named `dhruwang`, which has an initial value of 0. Then I set a condition in first question that if value of variable `dhruwang` is 0, then jump to Thank you card. But is does not seem to work  


https://github.com/user-attachments/assets/fa486cda-d0db-4e33-a0d9-69840668cc93



### Not able to save survey, when logic of some question contain an action which includes calculate operation on text variables  

https://github.com/user-attachments/assets/71cae7f6-83dd-421f-9910-13a377f41298


### We cannot make a question optional logically, So we can remove `is Skipped` from the dropdown for required questions   

<img width="832" alt="Screenshot 2024-09-10 at 11 23 17 AM" src="https://github.com/user-attachments/assets/308698f9-27ef-433e-aaa2-2013c6ca1b85">


### For multiple choice multi select question, if operator is `equals`, then user should be able to select multiple operands as we did in older logic (because response to multiple choice multiple select is an array)  

https://github.com/user-attachments/assets/01005529-625e-4b35-9798-1b48d8915eca




### is Submitted and is Skipped not working for multiple choice questions  

### Equal (=) and not equals (!=) not working for NPS and rating questions  


https://github.com/user-attachments/assets/c35e9fbe-bb33-4074-b5e7-da8e080f869c



### Issue with multiple conditions  

As you can see in the video below, I set two conditions joined with `and` which says, that if the open text question is skipped and rating is above 5 then show the ending card. But it shows the ending card even if open text question is filled  

  

https://github.com/user-attachments/assets/196309eb-38ac-47d8-8541-b351afa80117



### image preview in picture select logic settings   

Is is possible to show image preview in picture select logic dropdown instead of image name, similar to what we did in older logic editor   

<img width="838" alt="Screenshot 2024-09-10 at 11 56 11 AM" src="https://github.com/user-attachments/assets/141b27b5-9e1f-4bd4-9283-8c633c5743bd">

<img width="840" alt="Screenshot 2024-09-10 at 11 57 25 AM" src="https://github.com/user-attachments/assets/59930a71-f653-4ee2-8443-8d816adabdba">

### Logic in ranking question not working   

<img width="1275" alt="Screenshot 2024-09-10 at 1 18 24 PM" src="https://github.com/user-attachments/assets/06af8784-bfe0-49ce-a7e6-88e1f6b68dfc">



### We can now remove `is partially submitted` from matrix question as we do not allow partial submissions now   
<img width="880" alt="Screenshot 2024-09-10 at 1 20 58 PM" src="https://github.com/user-attachments/assets/12a6c69d-7214-408e-97db-613832471170">



### `is Skipped` in file upload not working  

https://github.com/user-attachments/assets/e02cdc81-7508-4190-8dba-572c07c1a0eb


### Can you also recheck logic evaluation using hidden field values 


Can you check these things ? 😊

2024-09-23 07:08 UTC, pandeymangg requested changes
thanks a lot for this biiiiiig PR @gupta-piyush19 great work on the code overall! 
I just had a couple of changes suggested mainly about consistency, pls take a look.
Found these issues in the UI for now, I'll test it more:

The text in the toast overflows if you have a logic error in a question that also uses recall, we also somehow leak this recall message
![image](https://github.com/user-attachments/assets/d67a40d0-a0ab-42f7-9739-fa8234a5260c)

Also found this issue that changing the question headline rapidly, the survey editor goes into the infinite render error when the logic editor is open

https://github.com/user-attachments/assets/d568d0f0-ca4e-4542-a793-8c5405b6ce8a

2024-09-23 11:05 UTC, gupta-piyush19 commented on packages/types/surveys/types.ts
> +const isInvalidOperatorsForQuestionType = (
getting circular dependency issue in this change

2024-09-23 15:30 UTC, pandeymangg commented
found a couple of more issues while testing:

1. The full recall string is visible here if a question contains recall:

![image](https://github.com/user-attachments/assets/e3a974e9-e2bb-4859-a118-7e628dedda3c)

2. The variable `score` here is a number and is equal to `0` but in the recall, it renders the fallback value, I think its treating the `0` as a `false` value, which shouldn't be the case in terms of number variables:

![image](https://github.com/user-attachments/assets/ae09424b-0b81-47f2-ba75-d7dd854e6ad4)

3. In this single select question, both the logic blocks contain the same logic (same condition and same action), but it only takes the last logic block (the second one in this case)

![image](https://github.com/user-attachments/assets/20e65eec-1e4c-4bad-bdfb-1bcd5820aff0)

2024-09-24 13:19 UTC, jobenjada commented
Overall, really cool! I've made a few tweaks in an effort to unify our dropdown menus (Segments, Logic, and rest of app)

as discussed:
<img width="436" alt="image" src="https://github.com/user-attachments/assets/f816aff9-f296-43b7-86ff-3f2fd5b5c76e">

spacing above Conditional Logic too high
<img width="518" alt="image" src="https://github.com/user-attachments/assets/2c2b8e32-af56-4ca2-bbd0-465513c5cabb">

lets add a bit of padding above the scroll bar
<img width="695" alt="image" src="https://github.com/user-attachments/assets/a5a20645-102b-48b9-a693-9665d78b9e3f">

increase width of toast globally (this can be wider in general if the toast message requires it. maybe `w-fit max-w-md` )
<img width="547" alt="image" src="https://github.com/user-attachments/assets/9db3ca7b-b724-4b4a-a715-7142d37a1a37">

and lets talk about performance on Slack 🤙

2024-09-25 05:35 UTC, Dhruwang requested changes
Logic for all question works really well, just noticed two issues that needs to be addressed 😊

When open text is configured to take number input, skipped condition is not working (works for strings)

https://github.com/user-attachments/assets/1ef70da3-5c54-4420-9de6-cf7f7bacbac4



Similar kind of issue with multiple select single


https://github.com/user-attachments/assets/8f334ff3-9664-47bc-963f-8c0a557c9383

2024-09-30 10:17 UTC, pandeymangg approved these changes

2024-09-30 10:36 UTC, merged