Formbricks Branding Signature
formbricks/formbricks pull request #305
Opened 2023-05-25 10:38 UTC by jobenjada

## What does this PR do?

Formbricks Branding Signature added (optional)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

In Preview 
![grafik](https://github.com/formbricks/formbricks/assets/72809645/c47604ef-61e6-45f6-9a52-ff39692a9f2c)

![grafik](https://github.com/formbricks/formbricks/assets/72809645/1389ffba-f2a5-4c60-b6ab-2e37a3f854f7)

Link Survey
![grafik](https://github.com/formbricks/formbricks/assets/72809645/0b810e76-c05b-4f59-a577-22c432a46342)

Widget
![grafik](https://github.com/formbricks/formbricks/assets/72809645/d4d17cc1-8ebd-4f42-b984-9f93cf1bac71)

Settings (will get an update at some point)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/3a000e49-52ff-47cf-b277-24d25ae76162)

## Checklist

Please test it through once :)

- [X] I ran `pnpm build` and `pnpm lint` to prevent build and linting errors
- [X] My contribitiom does not cause any warnings
- [X] I have removed all `console.logs`
- [X] I have merged the latest changes from main onto my branch with `git pull origin main`

2023-05-26 08:24 UTC, mattinannt requested changes
@jobenjada Currently the migration sets `formbricksSignature` to true (for all existing users) and the schema was altered to a default value of `false` but no migration was created.
Please fix to achieve the desired behaviour, e.g. first migration default false, afterwards a migration that changes default value to true (for new users).

2023-05-26 08:24 UTC, mattinannt commented on packages/js/src/components/FormbricksSignature.tsx
> +      <p className=" text-xs text-slate-400">
please prefix classes with `fb-` and remove space

2023-05-26 08:24 UTC, mattinannt requested changes
@jobenjada Currently the migration sets `formbricksSignature` to true (for all existing users) and the schema was altered to a default value of `false` but no migration was created.
Please fix to achieve the desired behaviour, e.g. first migration default false, afterwards a migration that changes default value to true (for new users).

2023-05-28 11:03 UTC, jobenjada commented
hoi :) added migrations and resolved merge conflicts 🙌

2023-05-29 09:15 UTC, jobenjada commented
Resolved merge conflicts. PR contains 2 migrations, ready from my side 🚀

2023-05-29 09:45 UTC, mattinannt approved these changes
good job 😊💪🎉

2023-05-29 09:46 UTC, merged