feat: Custom option value for multi choice questions
formbricks/formbricks pull request #3078
Opened 2024-09-01 17:16 UTC by SaiSawant1

## What does this PR do?
Allows users to enter custom values that are associated with the multi-choice options

This allows users to add values associated with the options in multi-choice options.
for example: 
jan --> 01
feb --> 02
this can come in handy when creating and exporting CSV files.
BY DEFAULT the option label are set as option value

Fixes #3068

![swappy-20240831_160721](https://github.com/user-attachments/assets/e45fdbee-3e03-4647-8dd2-fc93c01e1446)
![swappy-20240901_180727](https://github.com/user-attachments/assets/b9d68301-712e-4fbb-9eba-5713a9f86e77)
![swappy-20240901_180800](https://github.com/user-attachments/assets/28c2a441-dd6b-4149-904c-3bfbfa70bd18)

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-09-02 14:38 UTC, jobenjada commented
hey mate! Appreciate your work, but we'll keep this on a back burner for now. Since we neither designed the UI nor discussed the technical approach, it's not very likely if we can merge it soon.

2024-10-10 22:46 UTC, jobenjada approved these changes
love it, good work!

2024-10-23 10:15 UTC, mattinannt requested changes
The basic concept is good, but needs to get polished.

Since this is a concept only a very small fraction of Formbricks users need, we shouldn't bother users with confusing input fields they don't need and instead hide hide option by default and make the custom value optional.
<img width="1092" alt="Screenshot 2024-10-23 at 12 03 09" src="https://github.com/user-attachments/assets/5cce9234-b8eb-4e3e-8821-121e50211b68">

With the current concept changing a question where you don't want custom label leads to inconsistent states between old and new values if you don't update both labels. 
<img width="1169" alt="Screenshot 2024-10-23 at 12 11 31" src="https://github.com/user-attachments/assets/ca958776-1f5c-4d45-adb3-cf17a6069e77">

On my first try empty value led to this result in the survey summary:
<img width="460" alt="Screenshot 2024-10-23 at 11 27 37" src="https://github.com/user-attachments/assets/1b47f40c-e00d-4fcc-8826-7cb9613e1b2c">

In my opinion the custom value needs to be hidden by default and also should be optional and not populated with the current field value as this leads to either duplicated work + duplicated values or inconsistent state.

We will come up with a concept how to hide the custom value and make the necessary changes. Because of other features having higher priority right now we will tackle this after the next major release.

2025-01-28 11:31 UTC, mattinannt commented
Unfortunately, we couldn’t resolve this at the moment due to the significant implications for the data model and user experience. I'm closing this for now, but we’ll revisit this great work when the timing is right.

2025-01-28 11:31 UTC, closed without merging