chore: removes actions from the backend
formbricks/formbricks pull request #3106
Opened 2024-09-06 05:26 UTC by pandeymangg

## What does this PR do?
Removes Actions from the backend
Fixes https://github.com/formbricks/internal/issues/326

## How should this be tested?

- Actions should be removed

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-09-18 12:25 UTC, jobenjada requested changes
please also remove all references in the docs regarding Actions https://formbricks.com/docs/app-surveys/actions

2024-09-30 07:05 UTC, mattinannt requested changes

2024-09-30 07:05 UTC, mattinannt commented on packages/database/schema.prisma
> -  /// [ActionProperties]
These types should also be removed from `packages/database/json-types.ts` & `packages/database/zod-utils.ts`

2024-09-30 07:05 UTC, mattinannt commented on packages/types/segment.ts
I think we can also remove the `packages/types/actions.ts` file

2024-10-01 16:39 UTC, mattinannt approved these changes
Looks great! Thanks a lot for making the changes 😊🚀🔥
Let's get this merged!! 👏

2024-10-02 12:06 UTC, merged