feat: product configuration pages loading skeletons
formbricks/formbricks pull request #3262
Opened 2024-10-02 23:20 UTC by PratikAwaik

## What does this PR do?

Fixes #3213 

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

2024-10-06 22:32 UTC, jobenjada requested changes

2024-10-06 22:32 UTC, jobenjada commented on apps/web/app/(app)/environments/[environmentId]/product/(setup)/website-connection/loading.tsx
>  const LoadingCard = ({ title, description, skeletonLines }) => {
We're having this LoadingCard in each loading.tsx of the settings -> Feels like it should be its own component.

2024-10-06 22:32 UTC, jobenjada commented on apps/web/app/(app)/environments/[environmentId]/product/look/loading.tsx
> +              <div className="flex h-[95] max-h-[90%] w-4/6 flex-1 flex-col">
@PratikAwaik pls solve

2024-10-06 22:33 UTC, jobenjada commented
happy to add +300 points to the issue if you can check the organization settings as well as the account settings for their implementation of loading skeletons and unify it. They all also have their own LoadingCard component which doesnt make sense imo

2024-10-09 13:40 UTC, PratikAwaik commented
@jobenjada fixed PR comments as well as added unified loading in account and organization settings page

2024-10-10 18:08 UTC, tarunparmar752 commented
/assign

2024-10-10 22:47 UTC, jobenjada approved these changes

2024-10-10 23:26 UTC, merged