Feat/delete user account
formbricks/formbricks pull request #363
Opened 2023-06-12 22:32 UTC by fdis111

## As a user I want to delete my account

Fixes #349

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Login to the platform
- Click on the Settings option on the navigation bar 
- On the side navigation, click on profile below the account menu. 
- Click on the delete my account button 
- Confirm your deletion 

## Checklist

- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-06-13 06:21 UTC, jobenjada commented
Hey @fdis111 

I'm getting a build error:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/bdc075a8-2348-41cf-8b04-f61f3bb67990)


Please fix and remember to always run `pnpm build` before shipping :)

2023-06-13 12:59 UTC, jobenjada commented
Hey Francois! 

Overall the PR looks good, thanks for your contribution 🙏 

We have two questions:

1. **Filtering for admin:** In the issue description I mentioned that we will run into problems when you sign a team over to a person who is not an admin of the team.  Even though at this point all other users are admins, we plan to introduce more roles down the line. It would be great if you could check if there is an admin in the team and sign the team over to this user.

2. Assigning the admin role to the to-be-deleted user: Why do you make the user which will be deleted an admin before deletion?

3. Please run `git pull origin main` and resolve the merge conflict.

Thanks a lot!

2023-06-14 11:06 UTC, mattinannt requested changes
@fdis111 Thanks a lot for the PR 🤗 Generally great work, I made a few small suggestions for improvements that I marked in the code 😊💪.
The only critical part is that I haven't found the logic that deletes the team if the user is the only team member. This is needed to not have an orphaned team with no members left in the database after deleting the user.

2023-06-14 11:06 UTC, mattinannt commented on apps/web/app/environments/[environmentId]/settings/profile/editProfile.tsx
> +      disabled={!(inputValue === session.user.email)}>
Using `!==` would be easier to read:
```
disabled={inputValue !== session.user.email}
```

2023-06-19 08:57 UTC, mattinannt requested changes
@fdis111 Thanks a lot for the changes 😊 There was one case where I think we need a slightly different behavior and I also made some small notes. Otherwise it looks great 🎉

2023-06-19 08:57 UTC, mattinannt commented on apps/web/app/api/v1/users/me/route.ts
> +type MembershipRole = "admin" | "owner";
@fdis111 You can import `MembershipRole` from `@prisma/client`:

```import { MembershipRole } from "@prisma/client";```

2023-06-19 08:57 UTC, mattinannt commented on apps/web/app/api/v1/users/me/route.ts
> +            await deleteMembership(teamId, currentUser.id);
In this case, the person deleting the account is the owner of the team, and there are other members who are not admins (viewers, editors,..).
Just deleting the owner's membership and leaving the team without an owner and without an admin seems like a bad option. In this case, please delete the whole team and we will update the delete info text.

2023-06-19 08:57 UTC, mattinannt commented on apps/web/app/environments/[environmentId]/settings/profile/editProfile.tsx
> +        <p>
Please update to:
```jsx
          <p>
          Deleting your account will result in the permanent removal of all your personal information, saved preferences, and access to team data. If you are the owner of a team with other admins, the ownership of that team will be transferred to another admin.
        </p>
        <p className="py-5">
          Please note, however, that if you are the only member of a team or there is no other admin present, the team will be irreversibly deleted along with all associated data.
        </p>
```

2023-06-20 10:00 UTC, mattinannt requested changes
@fdis111 Thanks for the changes 💪 Everything works great 🎉
Please just add the last missing `await` and we are ready to merge the changes into main 🤗

2023-06-20 12:33 UTC, merged