add: move-from-prod-to-dev-rev
formbricks/formbricks pull request #392
Opened 2023-06-16 17:12 UTC by Ankur-Datta-4

## What does this PR do?

The change adds a feature where surveys could be moved from production environment to development environment, and vice-versa with just a button-click.
Fixes #228 (Feature)

 
[Loom video link](https://www.loom.com/share/6f3cf314bddb40f6a0b46a33099394a3?sid=07cdc1aa-e4ff-451f-ba71-1e36c1566067)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

This can be tested by choosing "move to prod env." in the drop-down of surveys in the dashboard (/environment/xx/surveys)

Tests which I ran:
- Move a survey from production to development env
- Move a survey from development to production env
- Ensure responses are not copied and only survey layout is copied

## Checklist

- [X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-06-16 18:52 UTC, jobenjada commented
@Ankur-Datta-4 works great, thanks!! 🙌 

@mattinannt pls review and merge

2023-06-19 09:41 UTC, mattinannt requested changes
@Ankur-Datta-4 Thanks for the PR 😊 I noticed a few things that need to be changed before we can merge the changes:

- Please use `Prettier` in VSCode to automatically format your code so that it looks consistent with the rest of the code in the repo.
- Please remove the period at the end of `Copy to Prod.`/`Copy to Dev.`.
- Please rename the copy of the survey and append `(copy)` to the name as we do when duplicating a survey.
- Currently the survey is copied without the triggers and audience settings. I discussed this with Johannes and we think that the expected behavior would be for the triggers and audience settings to be copied as well, so that you could, for example, use the exact survey in prod that you set up in dev. However, this comes with some added complexity: You will need to outsource your code to copy the survey to a custom api route so that you can use all the backend functionality. See the `duplicate` endpoint for more details ( https://github.com/formbricks/formbricks/blob/main/apps/web/pages/api/v1/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/duplicate.ts ). The attributeClasses and eventClasses may not already exist in this environment, so you'll need to check if an attributeClass / eventClass with the given name already exists or you'll need to create a new one and associate the survey with the new IDs.

I know the complexity of this ticket has increased significantly due to this change. Are you comfortable making these changes? 😊

2023-06-19 09:41 UTC, mattinannt commented on apps/web/app/environments/[environmentId]/surveys/SurveyList.tsx
> +  const copyToOtherEnvironment= async (surveyId)=>{
Please install and use the `prettier` VSCode plugin to format your changes into the right format (spacing, etc.).

2023-06-19 14:42 UTC, Ankur-Datta-4 commented
Sounds interesting, I'll work on duplicating the triggers & audience settings

2023-06-20 10:04 UTC, Ankur-Datta-4 commented
I've updated to make sure event-triggers are copied.
Here's a demo:

https://www.loom.com/share/c90b3e6a4bac48fa93b288674017c1fb?sid=00b6d321-a744-4192-b5b6-8aa0c767104b

Note:
- I have created a new route, modifying https://github.com/formbricks/formbricks/blob/main/apps/web/pages/api/v1/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/duplicate.ts 
- I've tested to ensure that: surveys get moved from dev-to-prod(or reverse) with/without triggers attached

2023-06-20 12:28 UTC, mattinannt reviewed
Thanks for the PR 💪 The code looks great and the functionality works 🎉😊.
Unfortunately we already had missing functionality in the existing duplicate survey functionality that `SurveyAttributeFilters` doesn't copy over. Would you be willing to add this functionality to the existing duplicate endpoint as well as the new `duplicate/[targetEnvironmentId]` endpoint?

2023-06-20 12:28 UTC, mattinannt commented on apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/duplicate/[targetEnvironmentId].ts
> +            createdAt: new Date(),
`createdAt` and `updatedAt` are automatically set by prisma when creating a new `eventClass` and don't need to be set explicitly.

2023-06-21 09:58 UTC, mattinannt commented
@Ankur-Datta-4 Thank you for adding the attributeFilters to the duplicate endpoint. Looks great!
Can you please also add this functionality to your new `.../duplicate/[targetEnvironmentId].ts` endpoint? 😊
I hope I'm not too impatient; if you're already working on it, don't let me pressure you 😉

2023-06-21 10:05 UTC, Ankur-Datta-4 commented
Yea working on it...facing some issues while testing. Will push it in a couple of hours

2023-06-21 10:59 UTC, Ankur-Datta-4 commented
I've followed the similar code (as done for events)
I've tested the same with previous quoted procedures.

2023-06-21 11:20 UTC, mattinannt requested changes
@Ankur-Datta-4 Thanks for the changes 💪🤗 Functionality-wise works great, just had a few suggestions for the code and would be great if you could change them.
Code formatting / prettier is the most important part of this to keep a consistent code style. As an alternative to using prettier, you can also run `pnpm format` in the project root; but using prettier is highly recommended 😊.

When these changes are in we are ready to merge into main 🎉💪

2023-06-21 11:20 UTC, mattinannt commented on apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/duplicate/[targetEnvironmentId].ts
> +    for (let i = 0; i < existingSurvey.attributeFilters.length; i++) {
a `for...of` loop is much easier to use for this functionality 😊
you can just write
```ts
for (const attributeFilter of existingSurvey.attributeFilters) {
...
}
```

2023-06-21 11:20 UTC, mattinannt commented on apps/web/pages/api/v1/environments/[environmentId]/surveys/[surveyId]/duplicate/[targetEnvironmentId].ts
> +          data:{
It looks like your code isn't automatically run through prettier. We use prettier to always format the code automatically in the same style. You can find prettier for VSCode here: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
It's also recommended to use it as default formatter and format on save so every time you save a file, it automatically formats the file according to the project rules 😊

2023-06-21 12:06 UTC, Ankur-Datta-4 commented
I've done the change. Today, I'm facing some issues with prettier like: 😌
![image](https://github.com/formbricks/formbricks/assets/75306530/eb3418ba-0d40-4408-a223-e6728b8fe481)

2023-06-21 14:01 UTC, mattinannt commented
> I've done the change. Today, I'm facing some issues with prettier like: 😌 ![image](https://user-images.githubusercontent.com/75306530/247540982-eb3418ba-0d40-4408-a223-e6728b8fe481.png)
> 
> Edit: pnpm format resulted in 603 changes. Im sure thats not what's required 😀

Interesting ;-) 
Can you share a screenshot of the files that were changed when you run `pnpm format`?
In my installation only changes to the `/duplicate/[targetEnvironmentId].ts` endpoint are made.
Would be good to know if different contributors have different `pnpm format` behaviour.

<img width="930" alt="Screenshot 2023-06-21 at 16 00 36" src="https://github.com/formbricks/formbricks/assets/675065/b30025a0-a97c-4e03-9947-a3d7c773f966">

2023-06-21 14:34 UTC, Ankur-Datta-4 commented
I see that it has modified every file there is! 😀
![image](https://github.com/formbricks/formbricks/assets/75306530/a8b5f990-a1ff-43bd-91f5-66aacfd9ed1c)

Every file from formbricks-com, web, demo, lib and database files

2023-06-23 09:47 UTC, mattinannt approved these changes
@Ankur-Datta-4 I changed the formatting in the last file and will merge the PR now 💪
Thanks a lot for this feature; awesome work 😊🤗

We will keep an eye on the problems with the `pnpm format` command, as I was unable to reproduce it at the moment.

2023-06-23 09:48 UTC, merged