[WIP] Feat/display survey on generic actions
formbricks/formbricks pull request #393
Opened 2023-06-17 03:42 UTC by Ashutosh-Bhadauriya

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-06-19 09:07 UTC, jobenjada commented
@Ashutosh-Bhadauriya Great work, works smoothly! 🙏 

@mattinannt Please do a final review

2023-06-21 11:51 UTC, mattinannt requested changes
Feature works great, thanks 😊🎉

When an existing user (an existing product) uses the formbricks-js widget and the exit-event or 50%-event is triggered, a new eventClass is created by the client's event endpoint ( `apps/web/pages/api/v1/client/environments/[environmentId]/events/index.ts` ). This public endpoint is only allowed to create `code` events, so the resulting event won't be an automatic event, but a code event. As a workaround, we can add a name check to this endpoint that will create an automatic event for an eventClass named `Exit Intent (Desktop)` or `50% Scroll` and a code event otherwise. It's a bit hacky, but I think it's the easiest way to implement a (temporary) data migration.
Do you want to make these changes to the code as well as a small clean-up in the formbricks-js init function as suggested below? 🤗

After that we are ready to merge the changes into the main 😊💪.

2023-06-21 12:15 UTC, Ashutosh-Bhadauriya commented on packages/js/src/lib/init.ts
> +  if(typeof document !== undefined){
@mattinannt sure, let me fix these 🙂

2023-06-21 16:31 UTC, Ashutosh-Bhadauriya commented
@mattinannt just pushed the changes. Please let me know😊

2023-06-23 10:16 UTC, mattinannt approved these changes
@Ashutosh-Bhadauriya Sorry that it took a bit longer to review the changes.
Thanks a lot for the PR and the updates, everything works great and package-js code looks good & clean now with the new automaticEvents functions 😊🎉💪

I just updated the formatting and merged the latest changes from main to make sure everything works fine. We use prettier to format the code and the easiest way to comply with the formatting rules is to use the [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and enable formatOnSave 😊

I will merge the changes into main now 💪

2023-06-23 10:17 UTC, merged

2023-06-23 10:52 UTC, Ashutosh-Bhadauriya commented
Thanks @mattinannt 😊 Actually I use prettier for formatting, but it stopped working after I moved to WSL. Sorry for the issue. I have fixed it now🙂