feat: added a option to set ordering of choices
formbricks/formbricks pull request #394
Opened 2023-06-17 10:14 UTC by Shubhdeep12

## What does this PR do?

Added the option for users to set the ordering of choices in Single and Multi-selection questions.
- Two Options: current order(default)  and random order
- Options other than "Other" will be randomized.
- Both in-app and standalone surveys are covered.

Fixes #248 
![image](https://github.com/formbricks/formbricks/assets/43654389/833e94ed-dcb6-4c17-a869-202e8dd2c59b)
![image](https://github.com/formbricks/formbricks/assets/43654389/2127176f-c91d-4f39-b29b-46dca1416838)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-06-17 12:13 UTC, jobenjada reviewed
overall, very good job, works well :) Well done keeping "Other" always as last option.

Some wording and UI remarks, other than that it was really good 🙌  thanks!!

2023-06-17 13:11 UTC, Shubhdeep12 commented on apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceMultiForm.tsx
Ok sure @jobenjada 

Then in that case, instead of setting choicesOrder as 'ordered' | 'random'
should we store a boolean named -  randomOrdering ?

2023-06-18 06:13 UTC, Shubhdeep12 commented
Hi @jobenjada, Done the requested changes of having Switch instead of Select. 

Also, made the change in the parameter. Now we will have a boolean named "randomOrdering" which will tell us whether the ordering is random or not.

2023-06-19 09:12 UTC, jobenjada commented on apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceMultiForm.tsx
Yes, a boolean seems to be the better solution. Please rework your PR accordingly 🙏

2023-06-19 09:13 UTC, Shubhdeep12 commented on apps/web/app/environments/[environmentId]/surveys/[surveyId]/edit/MultipleChoiceMultiForm.tsx
Added and pushed the same @jobenjada for your reference yesterday.

2023-06-19 09:17 UTC, jobenjada commented
@Shubhdeep12 Looks good, thanks a lot 🙌 

@mattinannt pls do final code review

2023-06-19 09:18 UTC, jobenjada reviewed
@Shubhdeep12 Looks good, thanks a lot 🙌

@mattinannt pls do final code review

2023-06-21 10:30 UTC, mattinannt requested changes
@Shubhdeep12 Thanks a lot for the PR 😊 Code looks great and functionality works great 💪

We have had some internal discussions about this feature. We have one case we didn't consider:
Take this common multiple choice question as an example:

```
Which programming languages do you like?
[ ] Python
[ ] Javascript
[ ] Go
[ ] None of the above
```
This is similar to the Other option because we always want `none of the above` at the bottom. This means we need three states for the `randomOrdering`: `none`, `all`, `exceptLast`.
with the following explanation to the user:
- `Keep choices in current order`.
- `Randomize all choices`.
- `Keep last choice and randomize other choices`.

So it's better to switch back to the drop-down list you had before. Sorry for the back and forth. Would you be okay with making these changes?
If you don't have the time to revamp it, it's totally understandable and me or another contributor can take over the changes.

I also thought about the naming and I would prefer `shuffleOption` over `randomOrdering` because it indicates that there are different states now.

We are also currently working on a zod scheme to validate surveys. Can you please add the new option to it as well? You can find it in `packages/types/v1/surveys.ts`.

Thanks a lot, we really appreciate your efforts and sorry again for the back and forth.

2023-06-21 14:58 UTC, Shubhdeep12 commented
No problem @mattinannt 
I can understand and this is a valid concern.

I'll update the code.

Thanks

2023-06-30 10:58 UTC, mattinannt commented
> Hi @mattinannt can you please explain this -
> 
> > We are also currently working on a zod scheme to validate surveys. Can you please add the new option to it as well? You can find it in `packages/types/v1/surveys.ts`.

Sure, we are currently in the process of switching from our Typescript types in `packages/types/surveys.ts`/`packages/types/questions.ts` to zod schemas that enable us to also do type validations during runtime. You can find the new types in the `packages/types/v1` folder.
To avoid errors in the new files/components that already use the new zod types, you also need to add the `shuffleOption` to `packages/types/v1/surveys.ts`

2023-06-30 14:16 UTC, Shubhdeep12 commented
Ok thanks @mattinannt 

Hi @jobenjada @mattinannt can you please review the PR now?
Thanks

2023-07-03 09:10 UTC, mattinannt requested changes
@Shubhdeep12 Sorry for the late response.
Thanks a lot for making the changes 🤗🎉 Looks great but while testing I noticed one thing that we need to change before we merge the changes:

We have different cases depending on whether we have an other option or not. If we don't have an other option the user should have all three options available. If he chooses `Except Last` all of the options except the last one (`6` in the screenshot) should be randomized. Currently in your code only the `other` option is not randomized.
<img width="785" alt="Screenshot 2023-07-03 at 10 59 57" src="https://github.com/formbricks/formbricks/assets/675065/a9c262e8-fe9e-41e2-9e86-5af4520a088b">
If an other option exists, it doesn't really make sense to randomize all options because the `other` option should always be last. Please remove the `all` option in that case.
<img width="629" alt="Screenshot 2023-07-03 at 11 05 26" src="https://github.com/formbricks/formbricks/assets/675065/e60abcee-afeb-446a-b782-da52c4f5fd98">

I also merged the latest changes from main into the branch and formatted the code using `pnpm format`. Please make sure to use the `prettier` plugin to format your code while editing or run `pnpm format` before you commit & push your changes 😊

2023-07-06 08:17 UTC, Shubhdeep12 commented
> @Shubhdeep12 Sorry for the late response. Thanks a lot for making the changes 🤗🎉 Looks great but while testing I noticed one thing that we need to change before we merge the changes:
> 
> We have different cases depending on whether we have an other option or not. If we don't have an other option the user should have all three options available. If he chooses `Except Last` all of the options except the last one (`6` in the screenshot) should be randomized. Currently in your code only the `other` option is not randomized. <img alt="Screenshot 2023-07-03 at 10 59 57" width="785" src="https://user-images.githubusercontent.com/675065/250509508-a9c262e8-fe9e-41e2-9e86-5af4520a088b.png"> If an other option exists, it doesn't really make sense to randomize all options because the `other` option should always be last. Please remove the `all` option in that case. <img alt="Screenshot 2023-07-03 at 11 05 26" width="629" src="https://user-images.githubusercontent.com/675065/250510987-e60abcee-afeb-446a-b782-da52c4f5fd98.png">
> 
> I also merged the latest changes from main into the branch and formatted the code using `pnpm format`. Please make sure to use the `prettier` plugin to format your code while editing or run `pnpm format` before you commit & push your changes 😊

got it @mattinannt 
will fix this.
thanks

2023-07-08 16:10 UTC, Shubhdeep12 commented
Hi @mattinannt can you please review the PR now? 
Thanks

2023-07-13 13:09 UTC, merged