feat: Added Rich text for questions and
formbricks/formbricks pull request #4040
Opened 2024-10-26 03:50 UTC by RajuGangitla

## What does this PR do?

This pr will add rich text to questions and descriptions .It will render the rich text in survey 

Fixes #4039

[screen-capture (25).webm](https://github.com/user-attachments/assets/598340d1-d4a7-4a61-b0cd-01b946d18d6f)

2024-10-31 02:25 UTC, jobenjada commented
big one, I know how hard you worked for this one! wont have time to review before the hackathon is over, but good work!

/award 2000

2024-10-31 02:28 UTC, RajuGangitla commented
Thank you @jobenjada 
I will complete this issue even though hacktoberfest ends

2024-10-31 02:39 UTC, jobenjada requested changes
<img width="835" alt="image" src="https://github.com/user-attachments/assets/8e4846dd-87dd-4177-a835-09f2f54bbe01">

1. Somehow the description field for Free Text does not "untoggle' - it always shows the rich text settings.

2. Please work in the feedback of CodeRabbit which makes sense!

3. In the logic editor, we see this
<img width="829" alt="image" src="https://github.com/user-attachments/assets/3d2d10cf-4fb3-4945-8439-360299231354">

4. Did you test what this looks like in the rest of the app?
- Summary view
- Integrations
- Email notifications
- etc

I can imagine this breaks a lot of things. 

We likely need an approach to sanitize the text from the HTML in the pipeline which pipes the question text to the different pieces of the app?

What do you think?

5. This needs to be inline and I cannot select any of the questions
<img width="460" alt="image" src="https://github.com/user-attachments/assets/96f7ca61-c4dd-4640-ad24-40a9272369ae">

6. on the Thank You card, this breaks:
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/0c810012-ce50-47c0-9c23-96ded786f739">

rich text not working on thank you card nor on the welcome card:
<img width="1666" alt="image" src="https://github.com/user-attachments/assets/6d82bc38-909f-4798-9fbb-ef8342609527">

etc.

Please test it through thoroughly with all the functionality in the survey editor and then downstream!

Thanks a lot for your great work so far :)

2024-10-31 02:44 UTC, RajuGangitla commented
@jobenjada I will try to fix all cases 

Just write down where it's failing 
Seems like I need to change at lot of places

2024-12-09 09:41 UTC, jobenjada commented
<img width="502" alt="image" src="https://github.com/user-attachments/assets/40128268-a535-466a-8fdc-46b32168318e">

another community member requested this

2024-12-09 09:43 UTC, RajuGangitla commented
@jobenjada is some one working on this one ?

2025-02-28 08:37 UTC, mattinannt commented
We are having some issues merging this PR because of feature incompatibility. We will sort this out internally and open a new PR once this is sorted.

2025-02-28 08:37 UTC, closed without merging