FEATURE: Tagging responses
formbricks/formbricks pull request #426
Opened 2023-06-22 07:40 UTC by pandeymangg

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-06-22 09:36 UTC, jobenjada commented
Hey Pandeyman!

Thanks so much, we really appreciate the work you put into this 😊 

I'll provide feedback on the UI / UX side of things, Matti will review the code. Here is my Feedback:

1. I broke it quite easily: When you add a tag with a capital letter, it gets saved as lower case. This breaks the tagging.
![grafik](https://github.com/formbricks/formbricks/assets/72809645/2067f49d-5f28-4bb6-9fce-97158cb08e5d)
https://tella.video/johanness-video-948o

2. When there are no tags, the UI is confusing: "No tags found" -> "Search tags" is contradictory
![grafik](https://github.com/formbricks/formbricks/assets/72809645/26313eb5-dc8d-4cc9-8ea3-a9de173d8160)
- Remove the icon
- Change placeholder tag: If no tags are found -> "Add tag..."
- If tags are found keep "Search tags..." but write "tag" with lower case

3. No hover indicator. Add `hover:bg-slate-50 hover:cursor-pointer` in the tag selection list:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/584b9f0a-8a4e-4148-98e4-8fe2bf625739)

4. Same here:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/ea571e64-0f3b-4744-987b-9e03eb653d8d)

5. No accessibility: Impossible to navigate with keyboard. When there is no tag in the selection the new tag should be added on "Enter"
![grafik](https://github.com/formbricks/formbricks/assets/72809645/4bd88215-de55-4095-839d-9b21afbb56eb)

6. When you click out of the Search bar but leave text inside, the next time you hit "Add Tag" it looks like this:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/5ccb1a7f-d591-45fd-a435-6907a6a42069)

7. Remove the Plus Icon, the layout itself already makes clear that this is a tag:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/0af631e9-2d36-4faa-9bd8-302265dc6e14)


**Tag Page:**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/d0dd34f1-b7c0-4819-b78d-bd6a86f852f9)
1. This placeholder doesnt make sense here. It would be easier to display the empty table with a "Tag a submission to find your list of tags here."
2. The line isn't needed

![grafik](https://github.com/formbricks/formbricks/assets/72809645/b11c82e5-c7ae-4759-8212-57710014fe8b)
3. Remove "tags". It suggests that there are several tags but the count is actually counting tagged responses. Just leave the number, should be clear.

4. Replace the plus icon with the Hashtag icon (heroicons)
![grafik](https://github.com/formbricks/formbricks/assets/72809645/a779e521-280c-441e-b250-b96a2659b48b)

5. Input field: Increase height a bit and make it fill the width of the cell. Always show the border (not only on hover) to make sure everyone understands that the tags can be changed there:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/2af9564d-e90c-485a-be76-6341731aee46)

6. Increase spacing-x between actions. I know I said it differently before but make Delete of variant="alert" (or whatever the red button is :) and Merge variant "secondary

7. Remove not needed space:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/affc9078-efc8-4306-bbad-c12eab392e93)

Thanks again, big contribution! 🙌

2023-06-22 11:35 UTC, mattinannt requested changes
@pandeymangg Thanks for the feature PR 💪 Looks great 😊
I marked a few things in the code that I came across.

Additionally a few things that can be improved 😊:

**Product -> Environment**
After talking with Johannes and seeing the endpoints, I think it would make more sense to move the tags as children to the environments instead of the product. A user who creates or deletes a tag in the dev environment doesn't expect those changes to be reflected in the production environment and also most of the functionality as well as the current endpoint structure is built for everything to be a child of the environment.
Sorry for the extra work you have due to this decision 😥

**PR Description**
Also in the PR the `How to test` field is quite important to me because it makes it much easier to test the PR and find & test the functionality that has been changed, so please fill this in for the next PR 😊.

**Migrations**.
You also have a few migrations due to your journey of testing different approaches. It would be great if you could merge them all into one. What I usually do to achieve this:
```bash
git checkout main
git pull
# Reset the database to the current state of main
pnpm prisma migrate dev
git checkout [your-branch]
# delete all migrations you have created in the branch
# Then pull the latest changes from main
git pull origin main
# Create a new migration that is the difference between the database state of main and your changes to the schema
pnpm prisma migrate dev
```

**Prettier**
We use prettier to format the code to have consistent formatting in all files. Please install prettier in VSCode ( https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode ) and make sure it is your default formatter and that you have `format on save` enabled.
Also, the `pnpm format` command formats all code files according to the prettier project rules, and if your code is already formatted when you write it, this command shouldn't change anything.

2023-06-22 12:46 UTC, pandeymangg commented on apps/web/app/environments/[environmentId]/surveys/[surveyId]/responses/ResponseTimeline.tsx
> +  const { product } = useProduct(environmentId);
Got it, I was just using it to get the product Id so I'll do that in the single response component

2023-06-22 12:47 UTC, pandeymangg commented on apps/web/pages/api/v1/environments/[environmentId]/product/[productId]/tags/[tagId]/index.ts
> +          return res.status(400).json({ message: "Tag already exists" });
Got it, I'll make these changes and update the PR

2023-06-25 13:43 UTC, mattinannt approved these changes
@pandeymangg Thanks a lot for the changes 🤗 Works much better now 😊

Unfortunately, there were some build bugs on my end that I had to fix.

The behaviour of the tag combobox needed some improvement, as the user didn't have the option to create tags that are partials of existing tags (e.g. "Feature" could not be created if a tag "Feature Request" already exists). Also added case-insensitive search of tags.

I will merge the changes now 😊

2023-06-25 13:43 UTC, merged