chore: Auth module revamp
formbricks/formbricks pull request #4335
Opened 2024-11-19 09:49 UTC by Dhruwang

## What does this PR do?

Fixes #4315 

Relocates and refactors auth code. 
Makes 2fa and SSO enterprise features

## How should this be tested?

Test auth, two factor , sso

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

2024-11-22 08:05 UTC, pandeymangg requested changes
great job on the PR @Dhruwang  already looks pretty good, I just added a few comments on the PR, please go through them, and also implement the new lib approach that we talked about on slack, thanks a lot 🙌

2024-11-22 08:05 UTC, pandeymangg commented on apps/web/modules/ee/two-factor-auth/components/disable-two-factor-modal.tsx
> +      form.reset();
I think we should leave the `router.refresh` function call here to sync the server state again

2024-11-22 08:33 UTC, Dhruwang commented on packages/types/user.ts
> +export const ZUserPassword = z
![Screenshot 2024-11-22 at 2 02 54 PM](https://github.com/user-attachments/assets/c7a32d03-0b72-4712-bf7b-feb5804880dd)

2024-11-22 08:56 UTC, Dhruwang commented on apps/web/modules/auth/forgot-password/actions.ts
> +export const forgotPasswordAction = actionClient
Here we removed error throwing few days back as a part of security fix, according to which user should not be able to find out which emails are registered and which arent on platform

2024-11-25 08:05 UTC, pandeymangg approved these changes
LGTM! 🚀

2024-11-25 17:21 UTC, mattinannt approved these changes

2024-11-26 08:40 UTC, merged