Server Rendering (previously Client): People Overview
formbricks/formbricks pull request #479
Opened 2023-07-04 09:19 UTC by ShubhamPalriwala

## What does this PR do?
[FOR-918](https://linear.app/formbricks/issue/FOR-918/rewrite-people-overview-page-to-server-components-and-services) Makes the People overview page server rendered (previously client rendered) as per Nextjs best practises

![Screenshot_2023-07-04-14-43-18_1920x1080](https://github.com/formbricks/formbricks/assets/55556994/9a027952-2916-44db-8bb3-92f66b554a59)

## Notes
- The `Link` tag was not working when I shifted the component inside the `page.tsx` hence I replaced it with the native `a` tag after which it started working
- Commented out the **Sessions** tab, let me know how to go about it

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-07-04 09:51 UTC, mattinannt requested changes
@ShubhamPalriwala 🎉💪 Looks great so far! I added a few comments 😊
Maybe you can also take a look at https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming and see if you can build a loading UI using the EmptySpaceFiller or something similar. We don't have this anywhere yet in our app but would like to use it :-)

2023-07-04 09:51 UTC, mattinannt commented on packages/lib/services/person.ts
> +      include: {
Please also check how this would affect other models (e.g. responses that include a person)

2023-07-04 09:51 UTC, mattinannt commented on packages/lib/services/person.ts
> +export const getAllPersons = async (): Promise<Array<TPerson>> => {
I would prefer the type `Promise<TPerson[]>` for better readability

2023-07-04 09:51 UTC, mattinannt commented on apps/web/app/environments/[environmentId]/people/page.tsx
> -import PeopleList from "./PeopleList";
The problem is that Next.js by default caches the values over the whole user session. Meaning when a user navigates with the next.js router through the app, even though they move away from the page and return, the person data stays the same. `revalidate = 0` forces Next.js to always get new data.

2023-07-04 13:49 UTC, ShubhamPalriwala commented on packages/lib/services/person.ts
> +      include: {
replaced include with `select`. and regd the additonal fields such as `createdAt` and `updatedAt`, will tackle that in a separate PR alltogether.

2023-07-05 08:07 UTC, ShubhamPalriwala commented
Hey @mattinannt, Implemented the Streaming using Suspense: 
https://www.loom.com/share/3c5381c4fb404f028561d32362cf30fb?sid=477f7bf9-3f3e-46aa-a32d-0a3663d291ec

2023-07-05 10:13 UTC, mattinannt requested changes
🎉 good job, I just have a few comments for restructuring the code.

2023-07-05 10:13 UTC, mattinannt commented on apps/web/app/environments/[environmentId]/people/Loading.tsx
please rename to lowercase `loading.tsx`

2023-07-05 10:13 UTC, mattinannt commented on apps/web/components/shared/LoadingTable.tsx
The LoadingTable is very specific to the people overview with the headers `users`, `user id`,..
I'm also currently in the process to relocate files as often as possible in the app directory to the pages/routes where they belong. So I think it would be the easiest to move all the content here into the `loading.tsx` and later check if we might need a generic and configurable skeleton component.

2023-07-05 10:13 UTC, mattinannt commented on apps/web/app/environments/[environmentId]/people/page.tsx
> +    <Suspense fallback={<Loading />}>
please remove the suspense and use the integrated next.js logic for that
https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming#instant-loading-states

(sorry for the back and forth, I'm also still learning :-D )

2023-07-05 11:06 UTC, mattinannt approved these changes
@ShubhamPalriwala 🎉💪 I will merge the changes now

2023-07-05 11:06 UTC, merged