Search template library
formbricks/formbricks pull request #616
Opened 2023-07-29 05:53 UTC by Meetcpatel

## What does this PR do?

Fixes #602 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-07-31 14:04 UTC, jobenjada commented
Hey @Meetcpatel 

Thanks for your work!

Please make sure that:

1. The search bar disables the the category filter so that it always shows the templates from all categories, not only the selected one.
2. Please set the bg of the Search Bar to white. Ideally, you would allow us to pass a className to the Search Bar Component in the same way shadcn does it so that we can custom style it in different places if we need.
3. Increase the default width of the Search Bar by 20%
4. Rework the search functionality with two words:

https://tella.video/johanness-video-gmmm

It's a bit odd that the first search term becomes irrelevant once the user adds a space behind it. 

What I was trying to say is that it would cool if the search doesnt only check for the string "improve trial" but also displays any template which contains "improve" and "trial" anywhere in the description or title but not neccessarily in that order. Does that make sense?

2023-08-04 12:59 UTC, jobenjada requested changes
Great PR, thanks for the refinement! Almost ready to merge :)

2023-08-04 12:59 UTC, jobenjada commented on packages/ui/components/SearchBox.tsx
> +import { SearchIcon } from "./../index";
pls replace with lucide or heroicon :)

2023-08-04 16:15 UTC, Meetcpatel commented on packages/ui/components/icons/SearchIcon.tsx
Ok

2023-08-04 16:41 UTC, Meetcpatel commented on packages/ui/components/icons/SearchIcon.tsx
Done!

2023-08-04 16:41 UTC, Meetcpatel commented on packages/ui/index.tsx
Done!

2023-08-04 16:42 UTC, Meetcpatel commented on packages/ui/components/SearchBox.tsx
> +import { SearchIcon } from "./../index";
Done Replaced!

2023-08-04 16:55 UTC, Meetcpatel commented
Done! I changed the code.

2023-08-05 05:29 UTC, Meetcpatel commented
Hide the clear button for input type "search"

2023-08-07 12:21 UTC, jobenjada approved these changes
great job, thanks for all the tweaking :)

2023-08-07 12:21 UTC, merged