Migrate Look & Feel Settings Page to Server-side
formbricks/formbricks pull request #672
Opened 2023-08-10 07:49 UTC by ShubhamPalriwala

## What does this PR do?
- Migrates the component to server-side
- Uses server actions
- Adds loading screen
- Follows 1 component per file convention
- Adds `updateProductLookAndFeel` server action
- Introduces a zod input type for the above action

The server action is created specifically for this only and if needed, can be made generalised to edit other values of  the  product as well! I kept it specific to this for now since we only need it here and whenever we want to expand, we can do it accordingly!

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## Checklist
- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-08-10 15:19 UTC, mattinannt requested changes
@ShubhamPalriwala thanks for the rewrite 😊 Structure looks good and I like it much better with no specific new type added. The services and types are like APIs which should be very generic and usable for different use cases.

I made a few suggestions about things I would change. They aren't necessarily things you programmed and could also be things that have been in the file before, but when we take the time to rewrite and revisit this page we can help to make it more consistent with the rest of the app 😊

2023-08-10 15:19 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/EditBrandColor.tsx
> +        type="submit"
as it isn't a form that gets submitted, please remove the ` type="submit"`

2023-08-10 15:19 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/EditHighlightBorder.tsx
> +    product.highlightBorderColor ? product.highlightBorderColor : DEFAULT_BRAND_COLOR
would be cleaner using `product.highlightBorderColor || DEFAULT_BRAND_COLOR`

2023-08-10 15:19 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/EditHighlightBorder.tsx
> +          type="submit"
please also remove the `type="submit"` here

2023-08-10 15:19 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/EditPlacement.tsx
> +export function EditPlacement({ product }: { product: TProduct }) {
Please also use an interface for the props here 😊

2023-08-10 15:19 UTC, mattinannt commented on packages/lib/services/product.ts
> +      throw new ResourceNotFoundError("Update for Product", productId);
This couldn't happen as Prisma would throw an error if the ressource that should be updated wasn't found.

2023-08-10 15:29 UTC, mattinannt commented on apps/web/app/(app)/environments/[environmentId]/settings/lookandfeel/page.tsx
Please add `export const revalidate = REVALIDATION_INTERVAL;` to make sure next.js doesn't cache indefinitely.

2023-08-10 16:41 UTC, ShubhamPalriwala commented
Hey @mattinannt, thanks for the detailed feedback and apologies for missing the details here! Just made all the requested changes! Please take a look!

2023-08-11 15:03 UTC, mattinannt approved these changes
@ShubhamPalriwala Looks great now, thanks a lot 😊💪🎉
The only thing I changed was the order of the attributes for updateProduct to make it more consistent with the other services (ressourceId first, then new object) 😊

I will merge the changes into main now! 🎉🚀

2023-08-11 15:04 UTC, merged