Feature: SingleUseSurveyLinks
formbricks/formbricks pull request #742
Opened 2023-08-29 18:47 UTC by ty-kerr

## What does this PR do?

This PR adds a single-use link option to Link Surveys. 

Added a suId field to the Response prisma model that is unique per survey.
Added a singleUse object in the survey prisma model to stored information about the single use options.

Added an extra option for enabling single-use links in the Response Options section when creating and editing surveys, here users can also modify the heading and subheading in the page that shows the user that the link has already been used.

In the survey summary, added a single use id to each of the response.

When single use survey is enabled, The link survey modal is modified to generate a link with an suId query parameter so users and send a working link right away, replace the embed button with a generate link button to generate new valid links.

Created a SurveyLinkUsed component to display when users open a link with a existing response for a single use survey.

Added additional logic in the server component for link surveys to check if the link survey has the single use option enabled, and to check if the SurveyLinkUsed should be displayed or not.

Fixes #72 
https://www.loom.com/share/f0a4a98a4f3f416ea74b0e076463adb6?sid=3f23ebc2-b22b-401d-9c3b-151dfc303d43

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

1. Create a survey with alteast two questions (for data pre-filling).
2. enable the single-use link option in the survey settings.
3. Use the survey link with suId query parameter to create responses.
4. Once the survey is completed with a link, try to reuse that link and expect the app to show a page stating the the link has been used already.
5. Generate new single-use links in from the summary page, by pressing the generate button in link survey.
6. Test survey link with userId and data-prefilling query parameters (each individually and together).
7. Try removing the singe-use option in the survey settings.
8. The survey should work multiple times with any link

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

2023-08-30 11:57 UTC, jobenjada commented
Hey @ty-kerr - thanks a lot for picking this up! It's looking really good 😍 

I managed to dig up a bug:

**Reloading the page mid survey**
I created a single use survey and after answering the first quesiton, I reloaded the page. This broke it and I am stuck at the skeleton. Even restarting the server didnt help so it broke the complete link survey. Ideally, the page would check if there is submission data for this survey in the local storage and if so, let the user continue filling out the survey. This would allow an undistrubed surveying experience even when the connection is getting lost inbetween.

Acutally, when I just close the tab and go back to the link in a new tab, I have the UX described (i can continue with the survey). Only the hard reload seems to break it.

**Local Storage not taking suId into account**
Im not entirely sure yet if this is a real problem, likely only when testing. But When I start a survey with 1 suId, close the tab and go to the survey with a new suId, it lets me continue the previous survey. So in that sense, the localStorage is not taking the suId into account. I think it would make sense to separate that, if only for people testing it and getting confused. Should be a quick fix :)

**Single Use breaks limit survey by responses**
This combination doesn't work. I can submit more than the limit due to the single use links:
<img width="680" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c03368f3-7b42-4ba0-a064-5a577571d6a3">

**Custom Survey Complete message text broken**
This is whats stored in the settings:
<img width="668" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/4d97c07e-3664-49a4-9b14-f84c0114e2a4">


This is what's shown:
<img width="502" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c89d7e78-88fe-42b4-99c9-a83d50e6549a">


**Showing "Link Used" message instead of Thank You page**
Only happened once, but showed me the Link Used message instead of the Thank You page. Dont know how to reproduce atm.
<img width="1124" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/aa985a98-72e4-4ec5-93f1-d218434d06e0">

**Update Share Modal UI**
Love you suggestion on updating the modal! 🤍  Actually, I would like to take it a step further to make sure every user understands that these are single use links :)

Here is a quick idea, not entirely sure if that makes sense though. Would love to get some feedback on this one before we build it:

![image](https://github.com/formbricks/formbricks/assets/72809645/0e8df3a8-a1d8-428e-a84a-39e665b861da)

Overall, tremendous work! 🤸

2023-08-31 14:14 UTC, ykburda commented
I tested the branch of ty-kerr for this feature. It is working as absoletly what it should be. I saw a great job. I tested all scenarios. And i think totally ready for production :) Thanks Kerr.

-  Only may i ask adding suID to responses of people page.

2023-09-02 02:46 UTC, ty-kerr commented
@jobenjada 

The issue with the limit survey response seems to be related to a bug in app/api/pipeline.ts. This also affects non single use surveys.

When for example, when the first question is Free Text and the user inputs a number string, e.g, '1234'. This number string gets converted into a date in line 20, causing a validation failure and early exit of the function, which mens the code that updates the status of the code is never executed.

perhaps another PR should be opened for this issue.

As for my progress, there is only the update to the Share modal. I like the approach you have suggested but i think it can be improved further if users have the option to select all of the links or individual links from the modal. We can separate each link to its own code block and make it click to copy. Once copied the background of that link could change to indicate it has been copied. And add a select all option somewhere.

2023-09-06 17:55 UTC, ty-kerr commented
The new design of the link survey modal for single used surveys looks great! ill implement that soon!

2023-09-07 18:15 UTC, ty-kerr commented
Updated the link modal for sharing single use survey at file: `LinkSingleUseSurveyModal.tx`

2023-09-15 15:04 UTC, mattinannt commented
@ty-kerr Thanks a lot for the PR :-) The feature looks pretty great :-)

Sorry for the late response. As Johannes already mentioned we were working on a revamp of the surveys experience which took longer than expected.
We now have one unified `@formbricks/surveys` package that handles the UI for the survey content in a single place (for both in-app and link surveys) and also for this cleaned up the LinkSurvey component a lot.
Because of these changes your feature now unfortunately has a lot of merge conflicts 😥 We would like to proceed with the merge of the feature; do you have capacity to solve these merge conflicts and adapt to our new LinkSurvey structure? 😊
If not, that's also fine and we can send one developer from our team to make the changes.

2023-09-15 17:26 UTC, ty-kerr commented
@mattinannt 

heyyy, i can handle the merge conflict!

2023-09-17 15:35 UTC, ty-kerr commented
@mattinannt 

merge conflicts solved. I updated the survey state to take in responseId and singleUseId in the constructor.

The singleUseId is used by the responseQueue to create responses with the suId field that is used for the feature.

The responseId is needed to ensure that when users have already created a response and refresh the survey in single use mode, the surveyState has the responseId  to update the existing response.

2023-09-18 04:58 UTC, ty-kerr commented
Another thing i noticed is that when users refresh the survey, their progress is reseted. Seems like the saved responses in local storage is not there anymore

2023-09-18 05:26 UTC, mattinannt commented
> Another thing i noticed is that when users refresh the survey, their progress is reseted. Seems like the saved responses in local storage is not there anymore

You are right; when we moved to the unified surveys package we needed to change some of the functionality. But I think we will add it again once the revamp of moving to server components is done 😊

2023-09-20 07:30 UTC, Dhruwang commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/LinkSingleUseSurveyModal.tsx
> +                  <div
We can add `key={singleUseId}` to avoid `Warning: Each child in a list should have a unique "key" prop`

2023-09-20 07:31 UTC, Dhruwang commented on apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/LinkSingleUseSurveyModal.tsx
> +import { Dialog, DialogContent } from "@formbricks/ui";
Can group all imports for `@formbricks/ui`

2023-09-22 19:03 UTC, ty-kerr commented
@Dhruwang  I just fixed the bug that caused the default messages to not show and added validation as you mentioned, except with AES 128 encryption.

2023-09-22 20:24 UTC, ykburda commented
This functionality can not be used , If you add any kind of reproducable external validation. Because how will be user will generate maybe thousand or ten thousand suid? Is there any simple way to generate such codes externally? In our requested design , user was creating hashed suids himself.

2023-09-23 02:58 UTC, ty-kerr commented
we could make the validation of single use survey links optional in the survey settings, and if users do want to use validation we can have users enter their own encryption key to be used.

we can always revert the latest commit and implement validation later, once a better solution is designed.

What do you guys think @ykburda @Dhruwang

2023-09-23 05:07 UTC, mattinannt commented
sorry for my late response, so hard keeping track of things during vacation.
@ty-kerr thanks a lot for the changes and the encryption.
But to be honest I would like to skip verification to make it more versatile so our users can use any string format (uuid, email address, number) and make it very easy to use. e.g. just append the users email adress as suid in your email sendi g script and you are good to go.
If we get a spam problem we can think about other ways, e.g upload a list of valid values or pattern matching or the encryption you implemented (but then optional) but for now I would start clean and leave out the encryption.

2023-09-23 05:47 UTC, mattinannt commented
Ok, looked through the code a bit more and the encryption feature could be cool when optional. And since it's already implemented we can use it :-) 
I would like to change the env variable name to `FORMBRICKS_ENCRYPTION_KEY` as we are currently building other features that use this env variable. Please make sure, that the variable is only used server side.
And can we add a toggle to the single use settings to use id encryption (default on)?

@ty-kerr Hope this doesn't change too much. If it's too much to ask for for now, you can also revert the last commit and we merge first :-)

2023-09-23 10:40 UTC, ykburda commented
Hi,
First of all, thanks tykerr for all best and quality works. I prefer optional. if encryptionkey in environment is blank , let it not verify or if it is filled do verify suid.

2023-09-23 11:33 UTC, ty-kerr commented
Ill work on making the encryption optional with your suggesstions @mattinannt. Should be done by monday (on vacation too at the moment). If we want the single use survey feature without validation merged first, i can prepare a branch for that, and open a new issue and implement the validation on a separate branch.

2023-09-23 18:43 UTC, mattinannt commented
@ty-kerr Thanks a lot :-) No worries, Monday sounds great and we merge everything together. Have a great vacation 🤗

2023-09-25 17:00 UTC, ty-kerr commented
just finished making the encryption optional.

here is a loom.
https://www.loom.com/share/e8d50f4cb55844afaa9511714826fd4e?sid=47e3a43f-6f0f-42f8-989d-a047584e59f6

2023-09-26 04:33 UTC, Dhruwang commented
@ty-kerr  Super cool 🤩🙌🏻

2023-10-02 14:16 UTC, ykburda commented
Please merge this function with giving 1000points to tykerr :)

2023-10-03 13:10 UTC, mattinannt requested changes

2023-10-03 13:10 UTC, mattinannt commented on turbo.json
> +        "NEXT_PUBLIC_FORMBRICKS_ENCRYPTION_KEY",
@Dhruwang I shouldn't be with `NEXT_PUBLIC`, right?

2023-10-03 13:10 UTC, mattinannt commented on apps/web/lib/surveys/surveys.ts
> +  const encryptedCuid = encryptAES128(env.FORMBRICKS_ENCRYPTION_KEY!, cuid);
Please move `FORMBRICKS_ENCRYPTION_KEY` to constants.ts and import from there. This way we can make sure that a build error is thrown when imported into a client component. Just to be sure ;-)

2023-10-03 16:25 UTC, mattinannt approved these changes
I made some additional changes:
- Moved the `FORMBRICKS_ENCRYPTION_KEY` to constants.ts file to make sure it's only called server-side
- Added zod validation to the length of the environment variable
- Added checks if encryption variable is set inside the helper methods before encrypting / decrypting
- Moved the helper functions to another file to prevent them being loaded client-side with other functions
- I added a check to only let users activate encryption when the environment variable is set

<img width="712" alt="Screenshot 2023-10-03 at 18 25 26" src="https://github.com/formbricks/formbricks/assets/675065/04a83476-4aca-484a-a674-87a6b47b6e81">

2023-10-03 16:26 UTC, merged