Fix/url shortener
formbricks/formbricks pull request #900
Opened 2023-10-02 07:17 UTC by joyal007

## What does this PR do?

Fixes #880

Added url shortener feature in formbricks

https://www.loom.com/share/cac9afdd921a43db91674c4e7e09b2f6?sid=d5413a82-a8b6-432e-b234-a9c21e8012af

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

2023-10-02 09:31 UTC, Dhruwang commented
Thank you @joyal007 for the PR, looks pretty great 💪😊

Here are few issues that I noticed

**Modal not resetting** 
After user closes link shorten modal, its fields should reset

https://github.com/formbricks/formbricks/assets/67850763/24c5f281-b593-4aff-8fc3-caa6a2519983

**Unique URL Pairs**
Ideally it should only have one short URL associated with one long URL, so before creating a new one, we can check whether short url for a given long url already exist 

https://github.com/formbricks/formbricks/assets/67850763/44223847-2d85-4053-9e14-d1a2235e7e7e

We can link icon here too
![Screenshot 2023-10-02 at 2 37 18 PM](https://github.com/formbricks/formbricks/assets/67850763/7ba7118f-7489-4e07-8c5f-629c1695ac1d)

Rename to [shortUrl]
<img width="194" alt="Screenshot 2023-10-02 at 2 59 49 PM" src="https://github.com/formbricks/formbricks/assets/67850763/7e97d821-046b-40bb-a104-ac8d377ca3af">

2023-10-02 09:53 UTC, Dhruwang requested changes

2023-10-02 09:53 UTC, Dhruwang commented on packages/lib/services/shortenedUrl.ts
> +export async function createShortenedUrl(shortUrl: string, longUrl: string) {
Add return types to both methods 😊

2023-10-02 13:23 UTC, joyal007 commented on apps/web/app/(app)/environments/[environmentId]/actions.ts
> +  const shortUrl = nanoid(10);
Thank you bro 
It helped a lot!

2023-10-04 17:35 UTC, closed without merging

2023-10-04 17:35 UTC, jobenjada commented
Thanks for your work so far, but as hinted at before, we're merging the first PR to come in on this issue.

Cheers!